# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ale = Country.create(
  :nombre => 'Alemania',
  :apodo => 'Legionarios',
  :grupo => 'F', 
  :escudo => 'public/countries/AleLo.png',
  :bandera => '../assets/banderas/alemania')

@aleG = ale

ale_coa = Coach.create(#Alemania
  :nombre => "Joachim",
  :apellido => "Löw",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1960,2,3),
  :ciudad_nacimiento => "Schönau")

CoachTeam.create(
  :debut => Date.new(2006,7,12),
  :coach_id => ale_coa.id,
  :country_id  => ale.id)

Player.create([{
  :nombre => "Marc-Andre",
  :apellido => "Ter Stegen",
  :fecha_nacimiento => Date.new(1992,4,30),
  :ciudad_nacimiento => "Mönchengladbach",
  :posicion => "Portero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2012,5,26),
  :participaciones => 2,
  :foto => "lololo",
  :goles => 0,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Manuel",
  :apellido => "Neuer",
  :fecha_nacimiento => Date.new(1986,3,27),
  :ciudad_nacimiento => "Gelsenkirchen-Buer",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2009,6,2),
  :participaciones => 3,
  :foto => "lololo",
  :goles => 0,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Kevin",
  :apellido => "Trapp",
  :fecha_nacimiento => Date.new(1990,7,8),
  :ciudad_nacimiento => "Merzig",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,6),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)

},
{
  :nombre => "Mats",
  :apellido => "Hummels",
  :fecha_nacimiento => Date.new(1988,12,16),
  :ciudad_nacimiento => "Bergisch Gladbach",
  :posicion => "Defensa Central",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2010,5,13),
  :participaciones => 2,
  :foto => "lololo",
  :goles => 5,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jerome",
  :apellido => "Boateng",
  :fecha_nacimiento => Date.new(1988,9,3),
  :ciudad_nacimiento => "Berlin",
  :posicion => "Defensa Central",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2009,10,10),
  :participaciones => 3,
  :foto => "lololo",
  :goles => 1,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Antonio",
  :apellido => "Rudiger",
  :fecha_nacimiento => Date.new(1993,3,3),
  :ciudad_nacimiento => "Berlin",
  :posicion => "Defensa Central",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2014,5,13),
  :participaciones => 24,
  :foto => "lololo",
  :goles => 1,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Niklas",
  :apellido => "Sule",
  :fecha_nacimiento => Date.new(1995,9,3),
  :ciudad_nacimiento => "Frankfurt am Main",
  :posicion => "Defensa Central",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,31),
  :participaciones => 11,
  :foto => "lololo",
  :goles => 0,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Matthias",
  :apellido => "Ginter",
  :fecha_nacimiento => Date.new(1994,1,19),
  :ciudad_nacimiento => "Freiburg",
  :posicion => "Defensa Central",
  :dorsal => 28,
  :apodo => "N/A",
  :debut =>  Date.new(2014,03,5),
  :participaciones => 18,
  :foto => "lololo",
  :goles => 0,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Marvin",
  :apellido => "Plattenhardt",
  :fecha_nacimiento => Date.new(1992,1,26),
  :ciudad_nacimiento => "Filderstadt",
  :posicion => "Lateral Izquierdo",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,6),
  :participaciones => 6,
  :foto => "lololo",
  :goles => 0,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jonas",
  :apellido => "Hector",
  :fecha_nacimiento => Date.new(1990,05,27),
  :ciudad_nacimiento => "Saarbrücken",
  :posicion => "Lateral Izquierdo",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,14),
  :participaciones => 38,
  :foto => "lololo",
  :goles => 3,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Joshua",
  :apellido => "Kimmich",
  :fecha_nacimiento => Date.new(1995,2,8),
  :ciudad_nacimiento => "Rottweil",
  :posicion => "Lateral Derecho",
  :dorsal => 32,
  :apodo => "N/A",
  :debut =>  Date.new(2011,11,12),
  :participaciones => 29,
  :foto => "lololo",
  :goles => 3,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Sebastian",
  :apellido => "Rudy",
  :fecha_nacimiento => Date.new(1990,2,28),
  :ciudad_nacimiento => "Villingen-Schwenning",
  :posicion => "Pivote",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,20),
  :participaciones => 25,
  :foto => "lololo",
  :goles => 1,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Toni",
  :apellido => "Kross",
  :fecha_nacimiento => Date.new(1990,1,4),
  :ciudad_nacimiento => "Greifswald",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2005,9,14),
  :participaciones => 83,
  :foto => "lololo",
  :goles => 12,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Leon",
  :apellido => "Goretzca",
  :fecha_nacimiento => Date.new(1995,2,6),
  :ciudad_nacimiento => "Bochum",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2010,10,15),
  :participaciones => 15,
  :foto => "lololo",
  :goles => 6,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ilkay",
  :apellido => "Gundogan",
  :fecha_nacimiento => Date.new(1986,3,29),
  :ciudad_nacimiento => "Rufisque",
  :posicion => "Mediocampista",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2014,5,31),
  :participaciones => 23,
  :foto => "lololo",
  :goles => 1,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Sami",
  :apellido => "Khedira",
  :fecha_nacimiento => Date.new(1987,4,4),
  :ciudad_nacimiento => "Stuttgart",
  :posicion => "Mediocampista",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2009,9,5),
  :participaciones => 75,
  :foto => "lololo",
  :goles => 7,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Mesut",
  :apellido => "Ozil",
  :fecha_nacimiento => Date.new(1988,10,15),
  :ciudad_nacimiento => "Gelsenkirchen",
  :posicion => "Mediocampistas",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2006,9,5),
  :participaciones => 90,
  :foto => "lololo",
  :goles => 23,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Julian",
  :apellido => "Brandt",
  :fecha_nacimiento => Date.new(1996,5,2),
  :ciudad_nacimiento => "Bremen",
  :posicion => "Extremo Izquierdo",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2011,6,7),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 1,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Julian",
  :apellido => "Draxler",
  :fecha_nacimiento => Date.new(1993,9,20),
  :ciudad_nacimiento => "Gladbeck",
  :posicion => "Extremo Izquierdo",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2010,10,8),
  :participaciones => 44,
  :foto => "lololo",
  :goles => 6,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Marco",
  :apellido => "Reus",
  :fecha_nacimiento => Date.new(1989,5,31),
  :ciudad_nacimiento => "Dortmund",
  :posicion => "Extremo Izquierdo",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2009,8,11),
  :participaciones => 31,
  :foto => "lololo",
  :goles => 9,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Thomas",
  :apellido => "Muller",
  :fecha_nacimiento => Date.new(1989,9,13),
  :ciudad_nacimiento => "Weilheim",
  :posicion => "Media Punta",
  :dorsal => 25,
  :apodo => "N/A",
  :debut =>  Date.new(2004,10,1),
  :participaciones => 91,
  :foto => "lololo",
  :goles => 38,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Timo",
  :apellido => "Werner",
  :fecha_nacimiento => Date.new(1996,3,6),
  :ciudad_nacimiento => "Stuttgart",
  :posicion => "Delantero Centro",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2010,11,9),
  :participaciones => 14,
  :foto => "lololo",
  :goles => 8,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Mario",
  :apellido => "Gomez",
  :fecha_nacimiento => Date.new(1985,7,10),
  :ciudad_nacimiento => "Riedlingen",
  :posicion => "Delantero Centro",
  :dorsal => 27,
  :apodo => "N/A",
  :debut =>  Date.new(2001,8,23),
  :participaciones => 75,
  :foto => "lololo",
  :goles => 31,
  :country_id => ale.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
