
bel = Country.create(
  :nombre => 'Bélgica',
  :apodo => 'Les Diables Rouges',
  :grupo => 'G',
  :escudo => 'public/countries/BelLo.png',
  :bandera => '../assets/banderas/belgica')

@belG = bel

bel_coa = Coach.create(#Belgium
  :nombre => "Roberto",
  :apellido => "Martínez",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1973,6,13),
  :ciudad_nacimiento => "Balaguer")

CoachTeam.create(
  :debut => Date.new(2017,7,4),
  :coach_id => bel_coa.id,
  :country_id  => bel.id)

Player.create([{ #Belgium
  :nombre => "Thibaut",
  :apellido => "Courtois",
  :fecha_nacimiento => Date.new(1992,5,11),
  :ciudad_nacimiento => "Bree",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2011,7,26),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Simon",
  :apellido => "Mignolet",
  :fecha_nacimiento => Date.new(1988,3,6),
  :ciudad_nacimiento => "Sint-Truiden",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2013,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Koen",
  :apellido => "Casteels",
  :fecha_nacimiento => Date.new(1992,6,25),
  :ciudad_nacimiento => "Bonheiden",
  :posicion => "Portero",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  Date.new(2015,1,21),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Tobias",
  :apellido => "Alderweireld",
  :fecha_nacimiento => Date.new(1989,3,2),
  :ciudad_nacimiento => "Wilrijk",
  :posicion => "Defensa central",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2015,7,8),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jan",
  :apellido => "Vertonghen",
  :fecha_nacimiento => Date.new(1987,4,24),
  :ciudad_nacimiento => "Sint-Niklaas",
  :posicion => "Defensa central",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2012,7,12),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Vincent",
  :apellido => "Kompany",
  :fecha_nacimiento => Date.new(1986,4,10),
  :ciudad_nacimiento => "Uccle",
  :posicion => "Defensa central",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2008,8,22),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Thomas",
  :apellido => "Vermaelen",
  :fecha_nacimiento => Date.new(1985,11,4),
  :ciudad_nacimiento => "Kapellen",
  :posicion => "Defensa central",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2014,8,9),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Dedryck",
  :apellido => "Boyata",
  :fecha_nacimiento => Date.new(1990,11,28),
  :ciudad_nacimiento => "Brussel",
  :posicion => "Defensa central",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2015,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Thomas",
  :apellido => "Meunier",
  :fecha_nacimiento => Date.new(1991,9,12),
  :ciudad_nacimiento => "Sainte-Ode",
  :posicion => "Lateral derecho",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2016,7,3),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Leander",
  :apellido => "Dendoncker",
  :fecha_nacimiento => Date.new(1995,4,15),
  :ciudad_nacimiento => "Passendale",
  :posicion => "Medio campo",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2014,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Youri",
  :apellido => "Tielemans",
  :fecha_nacimiento => Date.new(1995,4,15),
  :ciudad_nacimiento => "Passendale",
  :posicion => "Medio campo",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Axel",
  :apellido => "Witsel",
  :fecha_nacimiento => Date.new(1989,1,12),
  :ciudad_nacimiento => "Liège",
  :posicion => "Medio campo",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2017,1,3),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Mousa",
  :apellido => "Dembélé",
  :fecha_nacimiento => Date.new(1987,7,16),
  :ciudad_nacimiento => "Antwerpen",
  :posicion => "Medio campo",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2012,8,29),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Marouane",
  :apellido => "Fellaini",
  :fecha_nacimiento => Date.new(1987,11,22),
  :ciudad_nacimiento => "Etterbeek",
  :posicion => "Medio campo",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2013,9,2),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Kevin",
  :apellido => "De Bruyne",
  :fecha_nacimiento => Date.new(1991,6,28),
  :ciudad_nacimiento => "Drongen",
  :posicion => "Medio campo",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2015,8,30),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Eden",
  :apellido => "Hazard",
  :fecha_nacimiento => Date.new(1991,1,7),
  :ciudad_nacimiento => "La Louvière",
  :posicion => "Delantero",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2012,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Yannick",
  :apellido => "Carrasco",
  :fecha_nacimiento => Date.new(1993,9,4),
  :ciudad_nacimiento => "Ixelles",
  :posicion => "Delantero",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2018,2,26),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Thorgan",
  :apellido => "Hazard",
  :fecha_nacimiento => Date.new(1993,3,29),
  :ciudad_nacimiento => "La Louvière",
  :posicion => "Delantero",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2015,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Nacer",
  :apellido => "Chadli",
  :fecha_nacimiento => Date.new(1989,8,2),
  :ciudad_nacimiento => "La Louvière",
  :posicion => "Delantero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,29),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Adnan",
  :apellido => "Januzaj",
  :fecha_nacimiento => Date.new(1995,2,5),
  :ciudad_nacimiento => "Brussel",
  :posicion => "Delantero",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,12),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Romelu",
  :apellido => "Lukaku",
  :fecha_nacimiento => Date.new(1993,5,13),
  :ciudad_nacimiento => "Antwerpen",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,10),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Michy",
  :apellido => "Batshuayi",
  :fecha_nacimiento => Date.new(1993,10,2),
  :ciudad_nacimiento => "Brussel",
  :posicion => "Delantero",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2018,1,31),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Dries",
  :apellido => "Mertens",
  :fecha_nacimiento => Date.new(1987,5,6),
  :ciudad_nacimiento => "Leuven",
  :posicion => "Delantero",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2013,7,1),
  :participaciones => 1,
  :country_id => bel.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
