# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
bra = Country.create(
  :nombre => 'Brasil', 
  :apodo => 'Verde-amarela', 
  :grupo => 'E', 
  :escudo => 'public/countries/BraLo.png', 
  :bandera => '../assets/banderas/brasil')

@braG = bra

bra_coa = Coach.create(#Brasil
  :nombre => "Adenor",
  :apellido => "Bacchis",
  :apodo => "Tite",
  :fecha_nacimiento => Date.new(1961,5,25),
  :ciudad_nacimiento => "Caxias do Sul")

CoachTeam.create(
  :debut => Date.new(2016,06,16),
  :coach_id => bra_coa.id,
  :country_id  => bra.id)

Player.create([{ 
  :nombre => "Alisson",
  :apellido => "",
  :fecha_nacimiento => Date.new(1992,10,2),
  :ciudad_nacimiento => "Novo Hamburgo",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2015,10,14),
  :participaciones => 24,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ederson",
  :apellido => "",
  :fecha_nacimiento => Date.new(1993,8,17),
  :ciudad_nacimiento => "Osasco (SP)",
  :posicion => "Portero",
  :dorsal => 31,
  :apodo => "N/A",
  :debut =>  Date.new(2017,10,11),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Cassio",
  :apellido => "",
  :fecha_nacimiento => Date.new(1987,6,6),
  :ciudad_nacimiento => "Veranópolis",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,10),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)

},
{
  :nombre => "Marquinhos",
  :apellido => "",
  :fecha_nacimiento => Date.new(1994,05,14),
  :ciudad_nacimiento => "BSão Paulo",
  :posicion => "Defensa Central",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2013,11,17),
  :participaciones => 24,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Thiago",
  :apellido => "Silva",
  :fecha_nacimiento => Date.new(1984,9,22),
  :ciudad_nacimiento => "Rio de Janeiro",
  :posicion => "Defensa Central",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2008,8,13),
  :participaciones => 68,
  :foto => "lololo",
  :goles => 5,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Miranda",
  :apellido => "",
  :fecha_nacimiento => Date.new(1984,9,7),
  :ciudad_nacimiento => "Paranavaí",
  :posicion => "Defensa Central",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2009,4,2),
  :participaciones => 44,
  :foto => "lololo",
  :goles => 2,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Pedro",
  :apellido => "Geromel",
  :fecha_nacimiento => Date.new(1985,9,21),
  :ciudad_nacimiento => "São Paulo",
  :posicion => "Defensa Central",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2017,1,26),
  :participaciones => 11,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Marcelo",
  :apellido => "",
  :fecha_nacimiento => Date.new(1988,5,12),
  :ciudad_nacimiento => "Rio de Janeiro",
  :posicion => "Lateral Izquierdo",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2006,9,5),
  :participaciones => 51,
  :foto => "lololo",
  :goles => 5,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Filipe",
  :apellido => "Luis",
  :fecha_nacimiento => Date.new(1985,8,9),
  :ciudad_nacimiento => "Jaraguá do Sul",
  :posicion => "Lateral Izquierdo",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2009,10,15),
  :participaciones => 31,
  :foto => "lololo",
  :goles => 2,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Danilo",
  :apellido => "",
  :fecha_nacimiento => Date.new(1991,7,15),
  :ciudad_nacimiento => "Bicas",
  :posicion => "Lateral Derecho",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2011,9,15),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 14,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Fagner",
  :apellido => "",
  :fecha_nacimiento => Date.new(1989,6,11),
  :ciudad_nacimiento => "São Paulo",
  :posicion => "Lateral Derecho",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2017,1,26),
  :participaciones => 4,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Casemiro",
  :apellido => "Rudy",
  :fecha_nacimiento => Date.new(1992,2,23),
  :ciudad_nacimiento => "São José dos Santos",
  :posicion => "Pivote",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2011,9,15),
  :participaciones => 25,
  :foto => "lololo",
  :goles => 1,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Fernandinho",
  :apellido => "",
  :fecha_nacimiento => Date.new(1985,5,4),
  :ciudad_nacimiento => "Londrina",
  :posicion => "Pivote",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2006,11,15),
  :participaciones => 41,
  :foto => "lololo",
  :goles => 2,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Paulinho",
  :apellido => "",
  :fecha_nacimiento => Date.new(1988,7,25),
  :ciudad_nacimiento => "São Paulo",
  :posicion => "Mediocampista",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2011,9,15),
  :participaciones => 47,
  :foto => "lololo",
  :goles => 12,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Fred",
  :apellido => "",
  :fecha_nacimiento => Date.new(1993,3,5),
  :ciudad_nacimiento => "Belo Horizonte",
  :posicion => "Mediocampista",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,12),
  :participaciones => 7,
  :foto => "lololo",
  :goles => 0,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Renato",
  :apellido => "Augusto",
  :fecha_nacimiento => Date.new(1988,2,8),
  :ciudad_nacimiento => "Rio de Janeiro",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2007,6,30),
  :participaciones => 28,
  :foto => "lololo",
  :goles => 5,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Neymar",
  :apellido => "",
  :fecha_nacimiento => Date.new(1992,2,5),
  :ciudad_nacimiento => "Mogi das Cruzes",
  :posicion => "Extremo Izquierdo",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2009,10,24),
  :participaciones => 84,
  :foto => "lololo",
  :goles => 54,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Phillippe",
  :apellido => "Coutinho",
  :fecha_nacimiento => Date.new(1992,6,12),
  :ciudad_nacimiento => "Rio de Janeiro",
  :posicion => "Extremo Izquierdo",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2010,10,7),
  :participaciones => 35,
  :foto => "lololo",
  :goles => 9,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Taison",
  :apellido => "",
  :fecha_nacimiento => Date.new(1988,1,13),
  :ciudad_nacimiento => "Pelotas",
  :posicion => "Extremo Izquierdo",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2016,9,7),
  :participaciones => 6,
  :foto => "lololo",
  :goles => 1,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Douglas",
  :apellido => "Costa",
  :fecha_nacimiento => Date.new(1990,9,14),
  :ciudad_nacimiento => "Sapucaia do Sul",
  :posicion => "Extremo Izquierdo",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,12),
  :participaciones => 24,
  :foto => "lololo",
  :goles => 3,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "William",
  :apellido => "",
  :fecha_nacimiento => Date.new(1988,8,9),
  :ciudad_nacimiento => "Ribeirão Pires",
  :posicion => "Extremo Derecho",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2011,11,10),
  :participaciones => 54,
  :foto => "lololo",
  :goles => 8,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Roberto",
  :apellido => "Firminho",
  :fecha_nacimiento => Date.new(1991,10,2),
  :ciudad_nacimiento => "Maceió",
  :posicion => "Media Punta",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,12),
  :participaciones => 18,
  :foto => "lololo",
  :goles => 5,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Gabriel",
  :apellido => "Jesus",
  :fecha_nacimiento => Date.new(1997,4,3),
  :ciudad_nacimiento => "São Paulo",
  :posicion => "Delantero Centro",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,4),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 9,
  :country_id => bra.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])