
col = Country.create(
  :nombre => 'Colombia',
  :apodo => 'La Tricolor',
  :grupo => 'H',
  :escudo => 'public/countries/ColLo.png',
  :bandera => '../assets/banderas/colombia'
)

@colG = col

col_coa = Coach.create(#Colombia
  :nombre => "José",
  :apellido => "Pékerman",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1949,9,3),
  :ciudad_nacimiento => "Villa Domínguez")

CoachTeam.create(
  :debut => Date.new(2017,7,4),
  :coach_id => col_coa.id,
  :country_id  => col.id)

Player.create([{ #Colombia
  :nombre => "David",
  :apellido => "Ospina",
  :fecha_nacimiento => Date.new(1988,8,31),
  :ciudad_nacimiento => "Medellín",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2014,7,27),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Camilo",
  :apellido => "Vargas",
  :fecha_nacimiento => Date.new(1989,3,9),
  :ciudad_nacimiento => "Bogotá",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2018,1,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "José",
  :apellido => "Cuadrado",
  :fecha_nacimiento => Date.new(1985,6,1),
  :ciudad_nacimiento => "Valledupar",
  :posicion => "Portero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2013,1,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Davinson",
  :apellido => "Sánchez",
  :fecha_nacimiento => Date.new(1996,6,12),
  :ciudad_nacimiento => "Caloto",
  :posicion => "Defensa central",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2017,8,23),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Yerry",
  :apellido => "Mina",
  :fecha_nacimiento => Date.new(1994,9,23),
  :ciudad_nacimiento => "Guachené",
  :posicion => "Defensa central",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  Date.new(2018,1,11),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Óscar",
  :apellido => "Murillo",
  :fecha_nacimiento => Date.new(1988,4,18),
  :ciudad_nacimiento => "Armenia",
  :posicion => "Defensa central",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2016,1,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Johan",
  :apellido => "Mojica",
  :fecha_nacimiento => Date.new(1992,8,21),
  :ciudad_nacimiento => "Cali",
  :posicion => "Lateral izquierdo",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2017,8,18),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Santiago",
  :apellido => "Arias",
  :fecha_nacimiento => Date.new(1992,1,13),
  :ciudad_nacimiento => "Medellín  ",
  :posicion => "Lateral derecho",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2013,7,13),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Wilmar",
  :apellido => "Barrios",
  :fecha_nacimiento => Date.new(1993,10,16),
  :ciudad_nacimiento => "Cartagena de Indias",
  :posicion => "Medio campo",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,25),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Carlos",
  :apellido => "Sánchez",
  :fecha_nacimiento => Date.new(1986,2,6),
  :ciudad_nacimiento => "Quibdó",
  :posicion => "Medio campo",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2018,1,31),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jefferson",
  :apellido => "Lerma",
  :fecha_nacimiento => Date.new(1994,10,25),
  :ciudad_nacimiento => "Cerrito",
  :posicion => "Medio campo",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2016,7,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Abel",
  :apellido => "Aguilar",
  :fecha_nacimiento => Date.new(1985,1,6),
  :ciudad_nacimiento => "Cali",
  :posicion => "Medio campo",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2016,7,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Andrés",
  :apellido => "Uribe",
  :fecha_nacimiento => Date.new(1981,3,21),
  :ciudad_nacimiento => "Medellín",
  :posicion => "Medio campo",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2017,8,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "James",
  :apellido => "Rodríguez",
  :fecha_nacimiento => Date.new(1991,7,12),
  :ciudad_nacimiento => "Cúcuta",
  :posicion => "Medio campo",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,12),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Juan",
  :apellido => "Quintero",
  :fecha_nacimiento => Date.new(1993,1,18),
  :ciudad_nacimiento => "Medellín",
  :posicion => "Medio campo",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2018,1,24),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "José",
  :apellido => "Izquierdo",
  :fecha_nacimiento => Date.new(1992,7,7),
  :ciudad_nacimiento => "Pereira",
  :posicion => "Delantero",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2018,8,20),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Juan",
  :apellido => "Cuadrado",
  :fecha_nacimiento => Date.new(1988,5,26),
  :ciudad_nacimiento => "Necoclí",
  :posicion => "Delantero",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Radamel",
  :apellido => "Falcao",
  :fecha_nacimiento => Date.new(1986,2,10),
  :ciudad_nacimiento => "Santa Marta",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2013,7,1),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Luis",
  :apellido => "Muriel",
  :fecha_nacimiento => Date.new(1991,4,16),
  :ciudad_nacimiento => "Santo Tomás",
  :posicion => "Delantero",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2017,7,11),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Carlos",
  :apellido => "Bacca",
  :fecha_nacimiento => Date.new(1986,9,8),
  :ciudad_nacimiento => "Puerto Colombia",
  :posicion => "Delantero",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2017,8,16),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Miguel",
  :apellido => "Borja",
  :fecha_nacimiento => Date.new(1993,1,26),
  :ciudad_nacimiento => "Tierra Alta",
  :posicion => "Delantero",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2017,2,10),
  :participaciones => 1,
  :country_id => col.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
