coreasur = Country.create(:nombre => 'Corea del Sur', 
       :apodo => 'Los Guerreros Taeguk', 
       :grupo => 'F',
       :escudo => 'public/countries/KorLo.png', 
       :bandera => '../assets/banderas/coreaDelSur')

@cor = coreasur

corsur_coa = Coach.create(#Corea del Sur 
  :nombre => "Shin", 
  :apellido => "Tae-yong", 
  :apodo => "Asian Mourinho", 
  :fecha_nacimiento => Date.new(1969,4,11), 
  :ciudad_nacimiento => "Yeongdeok")

CoachTeam.create(
  :debut => Date.new(2017,7,4),
  :coach_id => corsur_coa.id,
  :country_id  => coreasur.id)

Player.create([{#Corea del Sur
              :nombre => "Seung-Gyu",
              :apellido => "Kim",
              :fecha_nacimiento => Date.new(1990,9,30),
              :ciudad_nacimiento => "Ulsan",
              :posicion => "Portero",
              :dorsal => 1,
              :apodo => "N/A",
              :debut =>  Date.new(2013,8,14),
              :participaciones => 31,
              :country_id => coreasur.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Jin-Hyeon",
              :apellido => "Kim",
              :fecha_nacimiento => Date.new(1987,9,6),
              :ciudad_nacimiento => "Suwon",
              :posicion => "Portero",
              :dorsal => 21,
              :apodo => "N/A",
              :debut =>  Date.new(2012,5,30),
              :participaciones => 14,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Hyeon-uh",
              :apellido => "Jo",
              :fecha_nacimiento => Date.new(1991,9,25),
              :ciudad_nacimiento => "Seoul",
              :posicion => "Portero",
              :dorsal => 23,
              :apodo => "N/A",
              :debut =>  Date.new(2017,11,14),
              :participaciones => 5,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ban-seok",
              :apellido => "Oh",
              :fecha_nacimiento => Date.new(1988,5,20),
              :ciudad_nacimiento => "Gwacheon",
              :posicion => "Defensa",
              :dorsal => 4,
              :apodo => "N/A",
              :debut =>  Date.new(2018,5,28),
              :participaciones => 1,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Young-gwon",
              :apellido => "Kim",
              :fecha_nacimiento => Date.new(1990,2,27),
              :ciudad_nacimiento => "Jeonju",
              :posicion => "Defensa",
              :dorsal => 19,
              :apodo => "N/A",
              :debut =>  Date.new(2010,11,8),
              :participaciones => 51,
              :goles => 2,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Hyun-soo",
              :apellido => "Jang",
              :fecha_nacimiento => Date.new(1991,9,28),
              :ciudad_nacimiento => "Seoul",
              :posicion => "Defensa",
              :dorsal => 20,
              :apodo => "N/A",
              :debut =>  Date.new(2013,6,18),
              :participaciones => 49,
              :goles => 3,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Seung-hyeon",
              :apellido => "Jung",
              :fecha_nacimiento => Date.new(1994,4,3),
              :ciudad_nacimiento => "Incheon",
              :posicion => "Defensa",
              :dorsal => 3,
              :apodo => "N/A",
              :debut =>  Date.new(2017,12,12),
              :participaciones => 5,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Young-seon",
              :apellido => "Yun",
              :fecha_nacimiento => Date.new(1998,10,4),
              :ciudad_nacimiento => "Hangul",
              :posicion => "Defensa",
              :dorsal => 5,
              :apodo => "N/A",
              :debut =>  Date.new(2015,11,17),
              :participaciones => 4,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ju-ho",
              :apellido => "Park",
              :fecha_nacimiento => Date.new(1987,1,16),
              :ciudad_nacimiento => "Seoul",
              :posicion => "Lateral Izquierdo",
              :dorsal => 6,
              :apodo => "N/A",
              :debut =>  Date.new(2012,1,18),
              :participaciones => 35,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Cheol",
              :apellido => "Hong",
              :fecha_nacimiento => Date.new(1990,9,17),
              :ciudad_nacimiento => "Hwaseong",
              :posicion => "Lateral Izquierdo",
              :dorsal => 14,
              :apodo => "N/A",
              :debut =>  Date.new(2011,2,9),
              :participaciones => 14,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Yong",
              :apellido => "Lee",
              :fecha_nacimiento => Date.new(1986,12,24),
              :ciudad_nacimiento => "Seoul",
              :posicion => "Lateral Derecho",
              :dorsal => 2,
              :apodo => "N/A",
              :debut =>  Date.new(2013,8,14),
              :participaciones => 25,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Sung-yong",
              :apellido => "Ki",
              :fecha_nacimiento => Date.new(1989,1,24),
              :ciudad_nacimiento => "Gwangju",
              :posicion => "Pivote",
              :dorsal => 16,
              :apodo => "N/A",
              :debut =>  Date.new(2008,9,5),
              :participaciones => 99,
              :goles => 10,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Woo-young",
              :apellido => "Jung",
              :fecha_nacimiento => Date.new(1989,12,14),
              :ciudad_nacimiento => "Ulsan",
              :posicion => "Pivote",
              :dorsal => 15,
              :apodo => "N/A",
              :debut =>  Date.new(2015,6,15),
              :participaciones => 27,
              :goles => 1,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Se-jong",
              :apellido => "Ju",
              :fecha_nacimiento => Date.new(1990,10,30),
              :ciudad_nacimiento => "Anyang",
              :posicion => "Pivote",
              :dorsal => 8,
              :apodo => "N/A",
              :debut =>  Date.new(2015,6,11),
              :participaciones => 9,
              :goles => 1,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Yo-han",
              :apellido => "Ko",
              :fecha_nacimiento => Date.new(1988,3,10),
              :ciudad_nacimiento => "Masan",
              :posicion => "Medio Centro",
              :dorsal => 22,
              :apodo => "N/A",
              :debut =>  Date.new(2010,10,14),
              :participaciones => 19,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Seon-min",
              :apellido => "Mun",
              :fecha_nacimiento => Date.new(1992,6,9),
              :ciudad_nacimiento => "Ulsan",
              :posicion => "Interior Derecho",
              :dorsal => 18,
              :apodo => "N/A",
              :debut =>  Date.new(2018,5,28),
              :participaciones => 1,
              :goles => 1,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Min-uh",
              :apellido => "Kim",
              :fecha_nacimiento => Date.new(1990,2,25),
              :ciudad_nacimiento => "Seoul",
              :posicion => "Interior Izquierdo",
              :dorsal => 12,
              :apodo => "N/A",
              :debut =>  Date.new(2013,8,14),
              :participaciones => 17,
              :goles => 1,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ja-cheol",
              :apellido => "Koo",
              :fecha_nacimiento => Date.new(1990,2,25),
              :ciudad_nacimiento => "Nonsan",
              :posicion => "Medio Centro Ofensivo",
              :dorsal => 13,
              :apodo => "N/A",
              :debut =>  Date.new(2008,2,17),
              :participaciones => 65,
              :goles => 19,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Jae-song",
              :apellido => "Lee",
              :fecha_nacimiento => Date.new(1992,8,10),
              :ciudad_nacimiento => "Ulsan",
              :posicion => "Medio Centro Ofensivo",
              :dorsal => 17,
              :apodo => "N/A",
              :debut =>  Date.new(2015,3,31),
              :participaciones => 32,
              :goles => 5,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Seung-woo",
              :apellido => "Lee",
              :fecha_nacimiento => Date.new(1998,1,6),
              :ciudad_nacimiento => "Gyeonggi-do",
              :posicion => "Extremo Izquierdo",
              :dorsal => 10,
              :apodo => "N/A",
              :debut =>  Date.new(2018,5,25),
              :participaciones => 1,
              :goles => 0,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Hee-chan",
              :apellido => "Hwaan",
              :fecha_nacimiento => Date.new(1996,1,26),
              :ciudad_nacimiento => "Chuncheon",
              :posicion => "Delantero Centro",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  Date.new(2016,9,1),
              :participaciones => 12,
              :goles => 2,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Shin-uk",
              :apellido => "Kim",
              :fecha_nacimiento => Date.new(1998,4,14),
              :ciudad_nacimiento => "Gwacheon",
              :posicion => "Delantero Centro",
              :dorsal => 9,
              :apodo => "N/A",
              :debut =>  Date.new(2010,9,1),
              :participaciones => 47,
              :goles => 10,
              :country_id => coreasur.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
}])