# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
costarica = Country.create(
  :nombre => 'Costa Rica', 
  :apodo => 'Los Ticos', 
  :grupo => 'E', 
  :escudo => 'public/countries/CosLo.png', 
  :bandera => '../assets/banderas/costaRica')

@costG = costarica

  costa_coa = Coach.create(#Costa Rica
  :nombre => "Óscar",
  :apellido => "Ramírez",
  :apodo => "El Machillo",
  :fecha_nacimiento => Date.new(1964,12,8),
  :ciudad_nacimiento => "Belén")

 CoachTeam.create(
  :debut => Date.new(2015,8,18),
  :coach_id => costa_coa.id,
  :country_id  => costarica.id, )


Player.create([{#COSTA RICA
              :nombre => "Keylor",
              :apellido => "Navas",
              :fecha_nacimiento => Date.new(1986,12,15),
              :ciudad_nacimiento => "San Isidro de El General",
              :posicion => "Portero",
              :dorsal => 1,
              :apodo => "N/A",
              :debut =>  Date.new(2008,3,1),
              :participaciones => 76,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Patrick",
              :apellido => "Pemberton",
              :fecha_nacimiento => Date.new(1982,4,24),
              :ciudad_nacimiento => "Limon",
              :posicion => "Portero",
              :dorsal => 18,
              :apodo => "N/A",
              :debut =>  Date.new(2006,3,15),
              :participaciones => 39,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Leonel",
              :apellido => "Moreira",
              :fecha_nacimiento => Date.new(1990,4,2),
              :ciudad_nacimiento => "Heredia",
              :posicion => "Portero",
              :dorsal => 23,
              :apodo => "N/A",
              :debut =>  Date.new(2009,3,2),
              :participaciones => 7,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Cristian",
              :apellido => "Gamboa",
              :fecha_nacimiento => Date.new(1989,9,24),
              :ciudad_nacimiento => "Liberia",
              :posicion => "Defensa",
              :dorsal => 16,
              :apodo => "N/A",
              :debut =>  Date.new(2010,1,26),
              :participaciones => 61,
              :foto => "Picture",
              :goles => 3,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ian",
              :apellido => "Smith",
              :fecha_nacimiento => Date.new(1998,3,6),
              :ciudad_nacimiento => "Limon",
              :posicion => "Defensa",
              :dorsal => 4,
              :apodo => "N/A",
              :debut =>  Date.new(2015,3,5),
              :participaciones => 1,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ronald",
              :apellido => "Matarrita",
              :fecha_nacimiento => Date.new(1994,7,9),
              :ciudad_nacimiento => "San Ramon",
              :posicion => "Defensa",
              :dorsal => 22,
              :apodo => "N/A",
              :debut =>  Date.new(2012,7,11),
              :participaciones => 9,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Bryan",
              :apellido => "Oviedo",
              :fecha_nacimiento => Date.new(1990,2,18),
              :ciudad_nacimiento => "San Ramon",
              :posicion => "Defensa",
              :dorsal => 8,
              :apodo => "N/A",
              :debut => Date.new(2010,1,26),
              :participaciones => 37,
              :foto => "Picture",
              :goles => 1,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Oscar",
              :apellido => "Duarte",
              :fecha_nacimiento => Date.new(1989,7,3),
              :ciudad_nacimiento => "Catarina",
              :posicion => "Defensa",
              :dorsal => 6,
              :apodo => "N/A",
              :debut =>  Date.new(2010,7,7),
              :participaciones => 33,
              :foto => "Picture",
              :goles => 2,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Giancarlo",
              :apellido => "Gonzales",
              :fecha_nacimiento => Date.new(1988,2,8),
              :ciudad_nacimiento => "San Jose",
              :posicion => "Defensa",
              :dorsal => 3,
              :apodo => "N/A",
              :debut =>  Date.new(2010,2,8),
              :participaciones => 66,
              :foto => "Picture",
              :goles => 2,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Francisco",
              :apellido => "Calvo",
              :fecha_nacimiento => Date.new(1992,7,8),
              :ciudad_nacimiento => "Guadalupe",
              :posicion => "Defensa",
              :dorsal => 15,
              :apodo => "N/A",
              :debut =>  Date.new(2011,7,2),
              :participaciones => 32,
              :foto => "Picture",
              :goles => 3,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Kendall",
              :apellido => "Waston",
              :fecha_nacimiento => Date.new(1988,1,1),
              :ciudad_nacimiento => "Limon",
              :posicion => "Defensa",
              :dorsal => 19,
              :apodo => "N/A",
              :debut =>  Date.new(2013,2,6),
              :participaciones => 23,
              :foto => "Picture",
              :goles => 3,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Jhonny",
              :apellido => "Acosta",
              :fecha_nacimiento => Date.new(1983,7,21),
              :ciudad_nacimiento => "San Carlos",
              :posicion => "Defensa",
              :dorsal => 2,
              :apodo => "N/A",
              :debut =>  Date.new(2011,3,29),
              :participaciones => 67,
              :foto => "Picture",
              :goles => 2,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "David",
              :apellido => "Guzman",
              :fecha_nacimiento => Date.new(1990,2,18),
              :ciudad_nacimiento => "Hatillo",
              :posicion => "Mediocampista",
              :dorsal => 20,
              :apodo => "N/A",
              :debut =>  Date.new(2010,8,16),
              :participaciones => 43,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Yeltsin",
              :apellido => "Tejeda",
              :fecha_nacimiento => Date.new(1992,3,17),
              :ciudad_nacimiento => "Siquirres",
              :posicion => "Mediocampista",
              :dorsal => 17,
              :apodo => "N/A",
              :debut =>  Date.new(2011,12,11),
              :participaciones => 45,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Celso",
              :apellido => "Borges",
              :fecha_nacimiento => Date.new(1988,5,27),
              :ciudad_nacimiento => "San Jose",
              :posicion => "Mediocampista",
              :dorsal => 5,
              :apodo => "N/A",
              :debut =>  Date.new(2008,3,9),
              :participaciones => 109,
              :foto => "Picture",
              :goles => 20,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Randall",
              :apellido => "Azofeifa",
              :fecha_nacimiento => Date.new(1984,12,30),
              :ciudad_nacimiento => "San Jose",
              :posicion => "Mediocampista",
              :dorsal => 14,
              :apodo => "N/A",
              :debut =>  Date.new(2005,2,5),
              :participaciones => 56,
              :foto => "Picture",
              :goles => 3,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Rodney",
              :apellido => "Wallace",
              :fecha_nacimiento => Date.new(1988,6,17),
              :ciudad_nacimiento => "San Jose",
              :posicion => "Mediocampista",
              :dorsal => 13,
              :apodo => "N/A",
              :debut =>  Date.new(2011,3,22),
              :participaciones => 25,
              :foto => "Picture",
              :goles => 4,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Bryan",
              :apellido => "Ruiz",
              :fecha_nacimiento => Date.new(1985,8,18),
              :ciudad_nacimiento => "San Jose",
              :posicion => "Mediocampista",
              :dorsal => 10,
              :apodo => "N/A",
              :debut =>  Date.new(2005,7,11),
              :participaciones => 108,
              :foto => "Picture",
              :goles => 23,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},              
{
              :nombre => "Daniel",
              :apellido => "Colindres",
              :fecha_nacimiento => Date.new(1985,1,10),
              :ciudad_nacimiento => "Alajuela",
              :posicion => "Mediocampista",
              :dorsal => 9,
              :apodo => "N/A",
              :debut =>  Date.new(2011,1,17),
              :participaciones => 12,
              :foto => "Picture",
              :goles => 0,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Christian",
              :apellido => "Bolaños",
              :fecha_nacimiento => Date.new(1984,5,17),
              :ciudad_nacimiento => "Hatillo",
              :posicion => "Mediocampista",
              :dorsal => 7,
              :apodo => "N/A",
              :debut =>  Date.new(2005,4,14),
              :participaciones => 80,
              :foto => "Picture",
              :goles => 8,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},              
{
              :nombre => "Johan",
              :apellido => "Venegas",
              :fecha_nacimiento => Date.new(1988,11,27),
              :ciudad_nacimiento => "Limon",
              :posicion => "Delantero",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  Date.new(2014,1,27),
              :participaciones => 44,
              :foto => "Picture",
              :goles => 9,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Joel",
              :apellido => "Campbell",
              :fecha_nacimiento => Date.new(1992,6,26),
              :ciudad_nacimiento => "Desemparados",
              :posicion => "Delantero",
              :dorsal => 12,
              :apodo => "N/A",
              :debut =>  Date.new(2011,3,9),
              :participaciones => 75,
              :foto => "Picture",
              :goles => 4,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Marco",
              :apellido => "Ureña",
              :fecha_nacimiento => Date.new(1990,3,5),
              :ciudad_nacimiento => "Palmichal",
              :posicion => "Delantero",
              :dorsal => 21,
              :apodo => "N/A",
              :debut =>  Date.new(2009,2,21),
              :participaciones => 61,
              :foto => "Picture",
              :goles => 14,
              :country_id => costarica.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
}])