# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
cro = Country.create(
       :nombre => 'Croacia', 
       :apodo => 'Vatreni', 
       :grupo => 'D', 
       :escudo => 'public/countries/CroLo.png',  
       :bandera => '../assets/banderas/croacia')

@croG = cro

 cro_coa =  Coach.create(#Croacia
  :nombre => "Zlatko",
  :apellido => "Dalić",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1966,10,26),
  :ciudad_nacimiento => "Livno")


CoachTeam.create(
  :debut => Date.new(2017,10,7),
  :coach_id => cro_coa.id,
  :country_id  => cro.id)

Player.create([{#Croacia
              :nombre => "Danijel",
              :apellido => "Subašić",
              :fecha_nacimiento => Date.new(1984,10,27),
              :ciudad_nacimiento => "Zadar",
              :posicion => "Portero",
              :dorsal => 23,
              :apodo => "N/A",
              :debut =>  Date.new(2009,11,14),
              :participaciones => 28,
              :country_id => cro.id,
              :goles => 0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Lovre",
              :apellido => "Kalinić",
              :fecha_nacimiento => Date.new(1990,4,3),
              :ciudad_nacimiento => "Split",
              :posicion => "Portero",
              :dorsal => 12,
              :apodo => "N/A",
              :debut =>  Date.new(2014,11,12),
              :participaciones => 0,
              :country_id => cro.id,
              :goles => 0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Dominik",
              :apellido => "Livaković",
              :fecha_nacimiento => Date.new(1995,1,9),
              :ciudad_nacimiento => "Zadar",
              :posicion => "Portero",
              :dorsal => 1,
              :apodo => "N/A",
              :debut =>  Date.new(2017,4,17),
              :participaciones => 20,
              :country_id => cro.id,
              :goles => 0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Dejan",
              :apellido => "Lovren",
              :fecha_nacimiento => Date.new(1989,7,5),
              :ciudad_nacimiento => "Zenica",
              :posicion => "Defensa Central",
              :dorsal => 6,
              :apodo => "N/A",
              :debut =>  Date.new(2009,10,8),
              :participaciones => 38,
              :country_id => cro.id,
              :goles => 2,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Domagoj",
              :apellido => "Vida",
              :fecha_nacimiento => Date.new(1989,4,21),
              :ciudad_nacimiento => "Osijek",
              :posicion => "Defensa Central",
              :dorsal =>  21,
              :apodo => "N/A",
              :debut =>  Date.new(2010,5,23),
              :participaciones =>  58,
              :country_id => cro.id,
              :goles =>  2,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Duje",
              :apellido => "Caleta–Car",
              :fecha_nacimiento => Date.new(1996,9,17),
              :ciudad_nacimiento => "Šibenik",
              :posicion => "Defensa Central",
              :dorsal => 15,
              :apodo => "N/A",
              :debut =>  Date.new(2018,6,3),
              :participaciones => 1,
              :country_id => cro.id,
              :goles => 0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Tin",
              :apellido => "Jedvaj",
              :fecha_nacimiento => Date.new(1995,11,28),
              :ciudad_nacimiento => "Zagreb",
              :posicion => "Defensa Central",
              :dorsal => 13,
              :apodo => "N/A",
              :debut =>  Date.new(2014,9,4),
              :participaciones =>  11,
              :country_id => cro.id,
              :goles =>  0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Vedran",
              :apellido => "Corluka",
              :fecha_nacimiento => Date.new(1986,2,5),
              :ciudad_nacimiento => "Derventa",
              :posicion => "Defensa Central",
              :dorsal =>  5,
              :apodo => "N/A",
              :debut =>  Date.new(2006,8,16),
              :participaciones => 96,
              :country_id => cro.id,
              :goles =>  4,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Ivan",
              :apellido => "Strinic",
              :fecha_nacimiento => Date.new(1987,7,17),
              :ciudad_nacimiento => "Split",
              :posicion => "Lateral Izquierdo",
              :dorsal =>  3,
              :apodo => "N/A",
              :debut =>  Date.new(2010,5,19),
              :participaciones => 42,
              :country_id => cro.id,
              :goles =>  0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Josip",
              :apellido => "Pivaric",
              :fecha_nacimiento => Date.new(1992,1,11),
              :ciudad_nacimiento => "Zagreb",
              :posicion => "Lateral Izquierdo",
              :dorsal =>  22,
              :apodo => "N/A",
              :debut =>  Date.new(2013,8,14),
              :participaciones =>  19,
              :country_id => cro.id,
              :goles =>  0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Sime",
              :apellido => "Vrsaljko",
              :fecha_nacimiento => Date.new(1992,1,10),
              :ciudad_nacimiento => "Rijeka",
              :posicion => "Lateral Derecho",
              :dorsal =>  2,
              :apodo => "N/A",
              :debut =>  Date.new(2011,2,9),
              :participaciones => 35,
              :country_id => cro.id,
              :goles =>  0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Milan",
              :apellido => "Badelj",
              :fecha_nacimiento => Date.new(1989,2,25),
              :ciudad_nacimiento => "Zagreb",
              :posicion => "Pivote",
              :dorsal =>  19,
              :apodo => "N/A",
              :debut =>  Date.new(2010,5,23),
              :participaciones =>  37,
              :country_id => cro.id,
              :goles =>  1,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Filip",
              :apellido => "Bradaric",
              :fecha_nacimiento => Date.new(1992,1,11),
              :ciudad_nacimiento => "Split",
              :posicion => "Pivote",
              :dorsal =>  14,
              :apodo => "N/A",
              :debut =>  Date.new(2016,11,15),
              :participaciones =>  4,
              :country_id => cro.id,
              :goles =>  0,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Ivan",
              :apellido => "Rakitic",
              :fecha_nacimiento => Date.new(1988,3,10),
              :ciudad_nacimiento => "Möhlin",
              :posicion => "Medio Centro",
              :dorsal =>  7,
              :apodo => "N/A",
              :debut =>  Date.new(2007,9,8),
              :participaciones => 89,
              :country_id => cro.id,
              :goles =>  14,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Mateo",
              :apellido => "Kovacic",
              :fecha_nacimiento => Date.new(1994,5,6),
              :ciudad_nacimiento => "Linz",
              :posicion => "Medio Centro",
              :dorsal =>  8,
              :apodo => "N/A",
              :debut =>  Date.new(2013,3,22),
              :participaciones => 40,
              :country_id => cro.id,
              :goles =>  1,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Marcelo",
              :apellido => "Brozovic",
              :fecha_nacimiento => Date.new(1992,11,16),
              :ciudad_nacimiento => "Zagreb",
              :posicion => "Medio Centro",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  Date.new(2014,6,6),
              :participaciones =>  34,
              :country_id => cro.id,
              :goles =>  6,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Luka",
              :apellido => "Modric",
              :fecha_nacimiento => Date.new(1985,9,9),
              :ciudad_nacimiento => "Zadar",
              :posicion => "Medio Centro",
              :dorsal =>  10,
              :apodo => "N/A",
              :debut =>  Date.new(2006,3,1),
              :participaciones =>  105,
              :country_id => cro.id,
              :goles =>  12,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Ivan",
              :apellido => "Perisic",
              :fecha_nacimiento => Date.new(1989,2,2),
              :ciudad_nacimiento => "Split",
              :posicion => "Extremo izquierdo",
              :dorsal =>  4,
              :apodo => "N/A",
              :debut =>  Date.new(2011,3,26),
              :participaciones =>  65,
              :country_id => cro.id,
              :goles =>  17,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Mario",
              :apellido => "Mandzukic",
              :fecha_nacimiento => Date.new(1986,5,21),
              :ciudad_nacimiento => "Slavonski Brod",
              :posicion => "Extremo Izquierdo",
              :dorsal =>  17,
              :apodo => "N/A",
              :debut =>  Date.new(2007,11,17),
              :participaciones =>  82,
              :country_id => cro.id,
              :goles =>  30,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Marko",
              :apellido => "Pjaca",
              :fecha_nacimiento => Date.new(1995,5,6),
              :ciudad_nacimiento => "Zagreb",
              :posicion => "Extremo izquierdo",
              :dorsal =>  20,
              :apodo => "N/A",
              :debut =>  Date.new(2014,9,4),
              :participaciones => 16,
              :country_id => cro.id,
              :goles =>  1,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Ante",
              :apellido => "Rebic",
              :fecha_nacimiento => Date.new(1993,9,21),
              :ciudad_nacimiento => "Split",
              :posicion => "Extremo izquierdo",
              :dorsal =>  18,
              :apodo => "N/A",
              :debut =>  Date.new(2013,8,14),
              :participaciones =>  15,
              :country_id => cro.id,
              :goles =>  1,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Andrej",
              :apellido => "Kramaric",
              :fecha_nacimiento => Date.new(1991,6,19),
              :ciudad_nacimiento => "Zagreb",
              :posicion => "Delantero Centro",
              :dorsal =>  9,
              :apodo => "N/A",
              :debut =>  Date.new(2014,9,14),
              :participaciones =>  30,
              :country_id => cro.id,
              :goles =>  8,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
},
{
              :nombre => "Nikola",
              :apellido => "Kalinic",
              :fecha_nacimiento => Date.new(1988,1,5),
              :ciudad_nacimiento => "Solin",
              :posicion => "Delantero Centro",
              :dorsal =>  16,
              :apodo => "N/A",
              :debut =>  Date.new(2008,5,24),
              :participaciones =>  41,
              :country_id => cro.id,
              :goles =>  15,
              :created_at => Date.new(2018,6.6),
              :updated_at => Date.new(2018,6.6)
}])

 Coach.create(#Croacia
  :nombre => "Ante",
  :apellido => "Čačić",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1953,9,29),
  :ciudad_nacimiento => "Zagreb")