# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
din = Country.create(
  :nombre => 'Dinamarca', 
  :apodo => 'El Tomate Mecánico', 
  :grupo => 'C', 
  :escudo => 'public/countries/DinLo.png', 
  :bandera => '../assets/banderas/dinamarca')

@dinG = din

 din_coa = Coach.create(#Dinamarca
  :nombre => "Åge",
  :apellido => "Hareide",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1953,9,23),
  :ciudad_nacimiento => "Hareid")

CoachTeam.create(
  :debut => Date.new(2016,3,1),
  :coach_id => din_coa.id,
  :country_id  => din.id)

Player.create([{ #Dinamarca
  :nombre => "Kasper",
  :apellido => "Schmeichel",
  :fecha_nacimiento => Date.new(1986,11,5),
  :ciudad_nacimiento => "Silkeborg",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2013,2,6),
  :participaciones => 34,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jonas",
  :apellido => "Lossl",
  :fecha_nacimiento => Date.new(1989,2,1),
  :ciudad_nacimiento => "Kolding",
  :posicion => "Portero",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2016,3,29),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Frederick",
  :apellido => "Ronnow",
  :fecha_nacimiento => Date.new(1992,8,4),
  :ciudad_nacimiento => "Horsens",
  :posicion => "Portero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,31),
  :participaciones => 7,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)

},
{
  :nombre => "Andreas",
  :apellido => "Christensen",
  :fecha_nacimiento => Date.new(1996,4,10),
  :ciudad_nacimiento => "Lillerød",
  :posicion => "Defensa Central",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2015,6,8),
  :participaciones => 15,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jannik",
  :apellido => "Vestergaard",
  :fecha_nacimiento => Date.new(1992,8,3),
  :ciudad_nacimiento => "Copenhagen",
  :posicion => "Defensa Central",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,14),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Simon",
  :apellido => "Kjaer",
  :fecha_nacimiento => Date.new(1989,3,26),
  :ciudad_nacimiento => "Horsens",
  :posicion => "Defensa Central",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2009,6,6),
  :participaciones => 77,
  :foto => "lololo",
  :goles => 3,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Zanka",
  :apellido => "Kopenhagen",
  :fecha_nacimiento => Date.new(1990,4,23),
  :ciudad_nacimiento => "",
  :posicion => "Defensa Central",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  Date.new(2008,11,19),
  :participaciones => 12,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jonas",
  :apellido => "Knudsen",
  :fecha_nacimiento => Date.new(1992,9,16),
  :ciudad_nacimiento => "Esbjerg",
  :posicion => "Lateral Izquierdo",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2014,5,28),
  :participaciones => 3,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Jens",
  :apellido => "Stryger",
  :fecha_nacimiento => Date.new(1991,2,21),
  :ciudad_nacimiento => "Sakskøbing",
  :posicion => "Lateral Derecho",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,31),
  :participaciones => 13,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Henrik",
  :apellido => "Dalsgaard",
  :fecha_nacimiento => Date.new(1989,7,27),
  :ciudad_nacimiento => "Roum",
  :posicion => "Lateral Derecho",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2016,3,24),
  :participaciones => 11,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Lasse",
  :apellido => "Schone",
  :fecha_nacimiento => Date.new(1986,5,27),
  :ciudad_nacimiento => "Glostrup",
  :posicion => "Pivote",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2009,8,12),
  :participaciones => 36,
  :foto => "lololo",
  :goles => 3,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "William",
  :apellido => "Kvist",
  :fecha_nacimiento => Date.new(1985,2,24),
  :ciudad_nacimiento => "Rønde",
  :posicion => "Pivote",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2007,8,22),
  :participaciones => 80,
  :foto => "lololo",
  :goles => 2,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Thomas",
  :apellido => "Delaney",
  :fecha_nacimiento => Date.new(1991,9,3),
  :ciudad_nacimiento => "Frederiksberg",
  :posicion => "Medio Centro",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2013,10,15),
  :participaciones => 27,
  :foto => "lololo",
  :goles => 4,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Lukas",
  :apellido => "Lerager",
  :fecha_nacimiento => Date.new(1993,7,12),
  :ciudad_nacimiento => "Gladsaxe",
  :posicion => "Medio Centro",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,6),
  :participaciones => 4,
  :foto => "lololo",
  :goles => 0,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Michael",
  :apellido => "Krohn-Dehli",
  :fecha_nacimiento => Date.new(1983,6,6),
  :ciudad_nacimiento => "Hvidovre",
  :posicion => "Medio Centro",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2006,10,11),
  :participaciones => 58,
  :foto => "lololo",
  :goles => 5,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Christian",
  :apellido => "Eriksen",
  :fecha_nacimiento => Date.new(1992,2,14),
  :ciudad_nacimiento => "Middelfart",
  :posicion => "Medio Centro Ofensivo",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2010,3,3),
  :participaciones => 78,
  :foto => "lololo",
  :goles => 22,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Pione",
  :apellido => "Sisto",
  :fecha_nacimiento => Date.new(1995,2,4),
  :ciudad_nacimiento => "Kampala",
  :posicion => "Extremo Izquierdo",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2015,9,4),
  :participaciones => 14,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Viktor",
  :apellido => "Fischer",
  :fecha_nacimiento => Date.new(1994,6,9),
  :ciudad_nacimiento => "Aarhus",
  :posicion => "Extremo Izquierdo",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2012,11,14),
  :participaciones => 19,
  :foto => "lololo",
  :goles => 3,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Nicolai",
  :apellido => "Jorgensen",
  :fecha_nacimiento => Date.new(1991,1,15),
  :ciudad_nacimiento => "Ballerup",
  :posicion => "Delantero Centro",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2011  ,11,11),
  :participaciones => 6,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Kasper",
  :apellido => "Dolberg",
  :fecha_nacimiento => Date.new(1997,10,6),
  :ciudad_nacimiento => "Silkeborg",
  :posicion => "Delantero Centro",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2016,11,11),
  :participaciones => 6,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Yussuf",
  :apellido => "Poulsen",
  :fecha_nacimiento => Date.new(1994,6,15),
  :ciudad_nacimiento => "Kopenhagen",
  :posicion => "Delantero Centro",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2014,10,11),
  :participaciones => 28,
  :foto => "lololo",
  :goles => 4,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Martin",
  :apellido => "Braithwaite",
  :fecha_nacimiento => Date.new(1991,6,5),
  :ciudad_nacimiento => "Esbjerg",
  :posicion => "Delantero Centro",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2013,6,5),
  :participaciones => 20,
  :foto => "lololo",
  :goles => 1,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Andreas",
  :apellido => "Cornelius",
  :fecha_nacimiento => Date.new(1993,3,16),
  :ciudad_nacimiento => "Kopenhagen",
  :posicion => "Delantero Centro",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2012,9,8),
  :participaciones => 18,
  :foto => "lololo",
  :goles => 4,
  :country_id => din.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
