# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ira = Country.create(
       :nombre => 'Iran', 
       :apodo => 'Los Príncipes de Persia', 
       :grupo => 'B', 
       :escudo => 'public/countries/IraLo.png', 
       :bandera => '../assets/banderas/iran')

@iraG = ira
 
 ira_coa =  Coach.create(#Iran
  :nombre => "Carlos",
  :apellido => "Queiroz",
  :apodo => "Príncipe de Persia",
  :fecha_nacimiento => Date.new(1953,3,1),
  :ciudad_nacimiento => "Nampula")

 CoachTeam.create(
  :debut => Date.new(2011,4,4),
  :coach_id => ira_coa.id,
  :country_id  => ira.id)

Player.create([{#Iran
              :nombre => "Aliereza",
              :apellido => "Beiranvand",
              :fecha_nacimiento => Date.new(1992,9,21),
              :ciudad_nacimiento => "Khorramabad",
              :posicion => "Portero",
              :dorsal => 1,
              :apodo => "N/A",
              :debut =>  Date.new(2015,1,4),
              :participaciones => 20,
              :foto => "Picture",
              :goles => 0,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Mohammad",
              :apellido => "Rashid",
              :fecha_nacimiento => Date.new(1989,5,18),
              :ciudad_nacimiento => "Gachsaran",
              :posicion => "Portero",
              :dorsal => 12,
              :apodo => "N/A",
              :debut =>  Date.new(2016,3,24),
              :participaciones => 3,
              :foto => "Picture",
              :goles => 0,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Amir",
              :apellido => "Abedzabeh",
              :fecha_nacimiento => Date.new(1993,4,25),
              :ciudad_nacimiento => "Tehran",
              :posicion => "Portero",
              :dorsal => 22,
              :apodo => "N/A",
              :debut =>  Date.new(2018,5,19),
              :participaciones => 1,
              :foto => "Picture",
              :goles => 0,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Morteza",
              :apellido => "Pouraliga",
              :fecha_nacimiento => Date.new(1992,4,19),
              :ciudad_nacimiento => "Badol",
              :posicion => "Defensa Central",
              :dorsal => 8,
              :apodo => "N/A",
              :debut =>  Date.new(2015,1,4),
              :participaciones => 25,
              :foto => "Picture",
              :goles => 2,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Majid",
              :apellido => "Hosseini",
              :fecha_nacimiento => Date.new(1996,6,20),
              :ciudad_nacimiento => "Karaj",
              :posicion => "Defensa Central",
              :dorsal => 19,
              :apodo => "N/A",
              :debut =>  Date.new(2018,5,18),
              :participaciones => 1,
              :foto => "Picture",
              :goles => 0,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Mohammad Reza",
              :apellido => "Khanzadeh",
              :fecha_nacimiento => Date.new(1992,1,20),
              :ciudad_nacimiento => "Teheran",
              :posicion => "Defensa Central",
              :dorsal => 13,
              :apodo => "N/A",
              :debut =>  Date.new(2012,12,9),
              :participaciones => 11,
              :foto => "Picture",
              :goles => 1,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Pejman",
              :apellido => "Montazeri",
              :fecha_nacimiento => Date.new(1983,9,6),
              :ciudad_nacimiento => "Ahvaz",
              :posicion => "Defensa Central",
              :dorsal => 15,
              :apodo => "N/A",
              :debut =>  Date.new(2008,12,19),
              :participaciones => 46,
              :foto => "Picture",
              :goles => 1,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Milad",
              :apellido => "Mohammadi",
              :fecha_nacimiento => Date.new(1993,9,29),
              :ciudad_nacimiento => "Teheran",
              :posicion => "Lateral Izquierdo",
              :dorsal => 5,
              :apodo => "N/A",
              :debut =>  Date.new(2015,6,11),
              :participaciones => 17,
              :foto => "Picture",
              :goles => 0,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ehsan",
              :apellido => "Hajsafi",
              :fecha_nacimiento => Date.new(1990,2,25),
              :ciudad_nacimiento => "Kashan",
              :posicion => "Lateral Izquierdo",
              :dorsal => 3,
              :apodo => "N/A",
              :debut =>  Date.new(2008,5,25),
              :participaciones => 93,
              :foto => "Picture",
              :goles => 6,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ramin",
              :apellido => "Rezaeian",
              :fecha_nacimiento => Date.new(1990,3,21),
              :ciudad_nacimiento => "Kashan",
              :posicion => "Lateral Derecho",
              :dorsal => 23,
              :apodo => "N/A",
              :debut =>  Date.new(2015,1,4),
              :participaciones => 26,
              :foto => "Picture",
              :goles => 2,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Omid",
              :apellido => "Ebrahimi",
              :fecha_nacimiento => Date.new(1987,9,16),
              :ciudad_nacimiento => "Neka",
              :posicion => "Pivote",
              :dorsal => 9,
              :apodo => "N/A",
              :debut =>  Date.new(2012,12,12),
              :participaciones =>28 ,
              :foto => "Picture",
              :goles => 0,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Roozbeh",
              :apellido => "Cheshmi",
              :fecha_nacimiento => Date.new(1993,6,24),
              :ciudad_nacimiento => "Teheran",
              :posicion => "Pivote",
              :dorsal => 4,
              :apodo => "N/A",
              :debut =>  Date.new(2017,8,31),
              :participaciones => 8,
              :foto => "Picture",
              :goles => 1,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Saeid",
              :apellido => "Ezatolahi",
              :fecha_nacimiento => Date.new(1996,10,1),
              :ciudad_nacimiento => "Bandar Anzali",
              :posicion => "Medio Centro",
              :dorsal => 6,
              :apodo => "N/A",
              :debut =>  Date.new(2015,6,11),
              :participaciones => 25,
              :foto => "Picture",
              :goles => 1,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ashkan",
              :apellido => "Dejagah",
              :fecha_nacimiento => Date.new(1986,7,5),
              :ciudad_nacimiento => "Teheran",
              :posicion => "Medio Centro Ofensivo",
              :dorsal => 21,
              :apodo => "N/A",
              :debut =>  Date.new(2012,2,29),
              :participaciones => 44,
              :foto => "Picture",
              :goles => 8,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Masoud",
              :apellido => "Shojaei",
              :fecha_nacimiento => Date.new(1984,6,9),
              :ciudad_nacimiento => "Shiraz",
              :posicion => "Medio Centro Ofensivo",
              :dorsal => 7,
              :apodo => "N/A",
              :debut =>  Date.new(2004,11,17),
              :participaciones => 72,
              :foto => "Picture",
              :goles => 8,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Vahid",
              :apellido => "Amiri",
              :fecha_nacimiento => Date.new(1988,4,2),
              :ciudad_nacimiento => "Khorramabad",
              :posicion => "Extremo Izquierdo",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  Date.new(2015,1,4),
              :participaciones => 43,
              :foto => "Picture",
              :goles => 1,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Mehdi",
              :apellido => "Torabi",
              :fecha_nacimiento => Date.new(1994,9,10),
              :ciudad_nacimiento => "Karaj",
              :posicion => "Extremo Izquierdo",
              :dorsal =>2 ,
              :apodo => "N/A",
              :debut =>  Date.new(2015,6,11),
              :participaciones => 15,
              :foto => "Picture",
              :goles => 4,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Alireza",
              :apellido => "Jahanbakhs",
              :fecha_nacimiento => Date.new(1993,8,11),
              :ciudad_nacimiento => "Jirandeh",
              :posicion => "Extremo Derecho",
              :dorsal => 18,
              :apodo => "N/A",
              :debut =>  Date.new(2013,10,15),
              :participaciones =>36 ,
              :foto => "Picture",
              :goles => 4,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Sadar",
              :apellido => "Azmoun",
              :fecha_nacimiento => Date.new(1995,1,1),
              :ciudad_nacimiento => "Gonbad",
              :posicion => "Delantero Centro ",
              :dorsal => 20,
              :apodo => "N/A",
              :debut =>  Date.new(2014,10,15),
              :participaciones => 32,
              :foto => "Picture",
              :goles => 23,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Karim",
              :apellido => "Ansarifard",
              :fecha_nacimiento => Date.new(1990,4,3),
              :ciudad_nacimiento => "Ardebil",
              :posicion => "Delantero Centro",
              :dorsal => 10,
              :apodo => "N/A",
              :debut =>  Date.new(1990,4,3),
              :participaciones => 62,
              :foto => "Picture",
              :goles => 16,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Mehdi",
              :apellido => "Taremi",
              :fecha_nacimiento => Date.new(1992,7,18),
              :ciudad_nacimiento => "Ardabil",
              :posicion => "Delantero Centro",
              :dorsal => 17,
              :apodo => "N/A",
              :debut =>  Date.new(2015,6,11),
              :participaciones => 24,
              :foto => "Picture",
              :goles => 11,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Saman",
              :apellido => "Ghoddos",
              :fecha_nacimiento => Date.new(1993,9,6),
              :ciudad_nacimiento => "Malmo",
              :posicion => "Delantero Centro",
              :dorsal => 14,
              :apodo => "N/A",
              :debut =>  Date.new(2017,10,5),
              :participaciones => 7,
              :foto => "Picture",
              :goles => 1,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Reza",
              :apellido => "Ghoochannejhad",
              :fecha_nacimiento => Date.new(1987,9,20),
              :ciudad_nacimiento => "Mashhad",
              :posicion => "Delantero Centro",
              :dorsal => 16,
              :apodo => "N/A",
              :debut =>  Date.new(1987,9,20),
              :participaciones => 40,
              :foto => "Picture",
              :goles => 17,
              :country_id => ira.id,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
}])
