japon = Country.create(:nombre => 'Japon', 
       :apodo => 'Samuráis',
       :grupo => 'H',
       :escudo => 'public/countries/JapLo.png', 
       :bandera => '../assets/banderas/japon')

@japonG = japon

 jap_coa = Coach.create(#Japon
  :nombre => "Akira",
  :apellido => "Nishino",
  :apodo => "N/A",
  :fecha_nacimiento => DateTime.new(1955,4,7),
  :ciudad_nacimiento => "Saitama")

CoachTeam.create(
  :debut => Date.new(2016,4,1),
  :coach_id => jap_coa.id,
  :country_id  => japon.id)

Player.create([{#Japon
              :nombre => "Kosuke",
              :apellido => "Nakamura",
              :fecha_nacimiento => DateTime.new(1995,2,27),
              :ciudad_nacimiento => "Tokio",
              :posicion => "Portero",
              :dorsal => 23,
              :apodo => "N/A",
              :debut =>  DateTime.new(2017,9,12),
              :participaciones => 3,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Masaaki",
              :apellido => "Higanshiguchi",
              :fecha_nacimiento => DateTime.new(1986,5,12),
              :ciudad_nacimiento => "Takatsuki, Osaka",
              :posicion => "Portero",
              :dorsal => 12,
              :apodo => "N/A",
              :debut =>  DateTime.new(2015,8,9),
              :participaciones => 4,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Eiji",
              :apellido => "Kawashima",
              :fecha_nacimiento => DateTime.new(1983,3,20),
              :ciudad_nacimiento => "Yono, Saitama",
              :posicion => "Portero",
              :dorsal => 1,
              :apodo => "N/A",
              :debut =>  DateTime.new(2008,2,17),
              :participaciones => 84,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Maya",
              :apellido => "Yoshida",
              :fecha_nacimiento => DateTime.new(1988,8,24),
              :ciudad_nacimiento => "Nagasaki",
              :posicion => "Defensa",
              :dorsal => 22,
              :apodo => "N/A",
              :debut =>  DateTime.new(2010,1,6),
              :participaciones => 82,
              :country_id => japon.id,
              :goles => 10,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Gen",
              :apellido => "Shoji",
              :fecha_nacimiento => DateTime.new(1992,12,11),
              :ciudad_nacimiento => "Kobe, Hyogo",
              :posicion => "Defensa",
              :dorsal => 3,
              :apodo => "N/A",
              :debut =>  DateTime.new(2015,3,31),
              :participaciones => 11,
              :country_id => japon.id,
              :goles => 1,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Tomoaki",
              :apellido => "Makino",
              :fecha_nacimiento => DateTime.new(1987,5,11),
              :ciudad_nacimiento => "Hiroshima",
              :posicion => "Defensa",
              :dorsal => 20,
              :apodo => "N/A",
              :debut =>  DateTime.new(2010,1,6),
              :participaciones => 32,
              :country_id => japon.id,
              :goles => 4,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Wantaru",
              :apellido => "Endo",
              :fecha_nacimiento => DateTime.new(1993,2,9),
              :ciudad_nacimiento => "Yokohama, Kanagawa",
              :posicion => "Defensa",
              :dorsal => 6,
              :apodo => "N/A",
              :debut =>  DateTime.new(2015,8,2),
              :participaciones => 11,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Naomichi",
              :apellido => "Ueda",
              :fecha_nacimiento => DateTime.new(1994,10,24),
              :ciudad_nacimiento => "Uto, Kumamoto",
              :posicion => "Defensa",
              :dorsal => 2,
              :apodo => "N/A",
              :debut =>  DateTime.new(2017,12,12),
              :participaciones => 3,
              :country_id => japon.id,
              :goles => 1,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Yuto",
              :apellido => "Nagamoto",
              :fecha_nacimiento => DateTime.new(1986,9,12),
              :ciudad_nacimiento => "Saijo, Ehime",
              :posicion => "Lateral Izquierdo",
              :dorsal => 5,
              :apodo => "N/A",
              :debut =>  DateTime.new(2008,5,24),
              :participaciones => 105,
              :country_id => japon.id,
              :goles => 3,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Hiroki",
              :apellido => "Sakai",
              :fecha_nacimiento => DateTime.new(1990,4,12),
              :ciudad_nacimiento => "Kashiwa, Chiba",
              :posicion => "Lateral Derecho",
              :dorsal => 19,
              :apodo => "N/A",
              :debut =>  DateTime.new(2012,5,23),
              :participaciones => 42,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Gotoku",
              :apellido => "Sakai",
              :fecha_nacimiento => DateTime.new(1991,3,14),
              :ciudad_nacimiento => "Nueva York",
              :posicion => "Lateral Derecho",
              :dorsal => 2,
              :apodo => "N/A",
              :debut =>  DateTime.new(2012,9,6),
              :participaciones => 40,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Hotaru",
              :apellido => "Yamaguchi",
              :fecha_nacimiento => DateTime.new(1990,10,6),
              :ciudad_nacimiento => "Nabari, Mie",
              :posicion => "Pivote",
              :dorsal => 16,
              :apodo => "N/A",
              :debut =>  DateTime.new(2013,7,21),
              :participaciones => 41,
              :country_id => japon.id,
              :goles => 2,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Makoto",
              :apellido => "Hasebe",
              :fecha_nacimiento => DateTime.new(1984,1,18),
              :ciudad_nacimiento => "Fujieda, Shizuoka",
              :posicion => "Pivote",
              :dorsal => 17,
              :apodo => "N/A",
              :debut =>  DateTime.new(2006,2,10),
              :participaciones => 110,
              :country_id => japon.id,
              :goles => 2,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Ryota",
              :apellido => "Oshima",
              :fecha_nacimiento => DateTime.new(1993,1,23),
              :ciudad_nacimiento => "Shizuoka",
              :posicion => "Medio Centro",
              :dorsal => 25,
              :apodo => "N/A",
              :debut =>  DateTime.new(2016,9,1),
              :participaciones => 5,
              :country_id => japon.id,
              :goles => 0,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Shinji",
              :apellido => "Kagawa",
              :fecha_nacimiento => DateTime.new(1989,3,17),
              :ciudad_nacimiento => "Kobe, Hyogo",
              :posicion => "Medio Centro Ofensivo",
              :dorsal => 10,
              :apodo => "N/A",
              :debut =>  DateTime.new(2008,5,24),
              :participaciones => 91,
              :country_id => japon.id,
              :goles => 29,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Takashi",
              :apellido => "Inui",
              :fecha_nacimiento => DateTime.new(1988,6,2),
              :ciudad_nacimiento => "Omihachiman, Shiga",
              :posicion => "Extremo Izquierdo",
              :dorsal => 18,
              :apodo => "N/A",
              :debut =>  DateTime.new(2009,1,20),
              :participaciones => 26,
              :country_id => japon.id,
              :goles => 2,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Genki",
              :apellido => "Haragushi",
              :fecha_nacimiento => DateTime.new(1992,5,6),
              :ciudad_nacimiento => "Nagaokakyo, Kyoto",
              :posicion => "Extremo Izquierdo",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  DateTime.new(2015,3,27),
              :participaciones => 23,
              :country_id => japon.id,
              :goles => 3,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Takashi",
              :apellido => "Usami",
              :fecha_nacimiento => DateTime.new(1992,5,6),
              :ciudad_nacimiento => "Nagaokakyo, Kyoto",
              :posicion => "Extremo Izquierdo",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  DateTime.new(2015,3,27),
              :participaciones => 23,
              :country_id => japon.id,
              :goles => 3,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Genki",
              :apellido => "Haraguchi",
              :fecha_nacimiento => DateTime.new(1991,5,9),
              :ciudad_nacimiento => "Kumagaya, Saitama",
              :posicion => "Extremo Izquierdo",
              :dorsal => 11,
              :apodo => "N/A",
              :debut =>  DateTime.new(2011,10,7),
              :participaciones => 32,
              :country_id => japon.id,
              :goles => 6,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Yuya",
              :apellido => "Osako",
              :fecha_nacimiento => DateTime.new(1990,5,18),
              :ciudad_nacimiento => "Kaseda, Kagoshima",
              :posicion => "Media Punta",
              :dorsal => 15,
              :apodo => "N/A",
              :debut =>  DateTime.new(2013,7,21),
              :participaciones => 28,
              :country_id => japon.id,
              :goles => 7,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Shinji",
              :apellido => "Okazaki",
              :fecha_nacimiento => DateTime.new(1986,4,16),
              :ciudad_nacimiento => "Takarazuka, Hyogo",
              :posicion => "Delantero Centro",
              :dorsal => 9,
              :apodo => "N/A",
              :debut =>  DateTime.new(2008,10,9),
              :participaciones => 112,
              :country_id => japon.id,
              :goles => 50,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
},
{
              :nombre => "Yoshinori",
              :apellido => "Muto",
              :fecha_nacimiento => DateTime.new(1992,7,15),
              :ciudad_nacimiento => "Setagaya, Tokio",
              :posicion => "Delantero Centro",
              :dorsal => 14,
              :apodo => "N/A",
              :debut =>  DateTime.new(2014,9,5),
              :participaciones => 23,
              :country_id => japon.id,
              :goles => 2,
              :created_at => Date.new(2018,6,6),
              :updated_at => Date.new(2018,6,6)
}])