# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

marruecos = Country.create(
  :nombre => 'Marruecos',
  :apodo => 'Los leones del atlas',
  :grupo => 'B',
  :escudo => 'public/countries/MorLo.png',
  :bandera => '../assets/banderas/marruecos')

  @marru = marruecos

 mar_coa = Coach.create(#Marruecos
  :nombre => "Herve",
  :apellido => "Renard",
  :apodo => "N/A",
  :fecha_nacimiento => DateTime.new(1968,9,30),
  :ciudad_nacimiento => "Aix-les-Bains")

CoachTeam.create(
  :debut => Date.new(1999,4,2),
  :coach_id => mar_coa.id,
  :country_id  => marruecos.id)

Player.create([{ #Marruecos
  :nombre => "Yassine",
  :apellido => "Bounou",
  :fecha_nacimiento => Date.new(1991,4,5),
  :ciudad_nacimiento => "Montreal",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "Bono",
  :debut =>  DateTime.new(2010,7,1),
  :participaciones => 10,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ahmed",
  :apellido => "Tagnaouti",
  :fecha_nacimiento => DateTime.new(1996,4,5),
  :ciudad_nacimiento => "Casablanca",
  :posicion => "Portero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,10,10),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Munir",
  :apellido => "El Haddadi",
  :fecha_nacimiento => DateTime.new(1995,9,1),
  :ciudad_nacimiento => "San Lorenzo de El Escorial",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  DateTime.new(2014,8,24),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)

},
{
  :nombre => "Medhi",
  :apellido => "Benatia",
  :fecha_nacimiento => DateTime.new(1987,4,17),
  :ciudad_nacimiento => "Courcouronnes",
  :posicion => "Defensa",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  DateTime.new(2008,11,19),
  :participaciones => 60,
  :foto => "lololo",
  :goles => 2,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Manuel",
  :apellido => "da Costa",
  :fecha_nacimiento => DateTime.new(1986,5,6),
  :ciudad_nacimiento => "Saint-Max",
  :posicion => "Defensa",
  :dorsal => 34,
  :apodo => "N/A",
  :debut =>  DateTime.new(2014,5,23),
  :participaciones => 4,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Hamza",
  :apellido => "Mendyl",
  :fecha_nacimiento => DateTime.new(1997,10,21),
  :ciudad_nacimiento => "Casablanca",
  :posicion => "Lateral izquierdo",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  DateTime.new(2016,9,4),
  :participaciones => 3,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Achraf",
  :apellido => "Hakimi Mouh",
  :fecha_nacimiento => DateTime.new(1998,11,4),
  :ciudad_nacimiento => "Madrid",
  :posicion => "Lateral derecho",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  DateTime.new(2016,10,11),
  :participaciones => 7,
  :foto => "lololo",
  :goles => 2,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Romain",
  :apellido => "Saïss",
  :fecha_nacimiento => DateTime.new(1990,3,26),
  :ciudad_nacimiento => "Bourg-de-Péage",
  :posicion => "Pivote",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  DateTime.new(2012,11,14),
  :participaciones => 20,
  :foto => "lololo",
  :goles => 1,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Youssef",
  :apellido => "Aït Bennasser",
  :fecha_nacimiento => DateTime.new(1996,7,7),
  :ciudad_nacimiento => "Toul",
  :posicion => "Medio centro",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,3,26),
  :participaciones => 11,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Sofyan",
  :apellido => "Amrabat",
  :fecha_nacimiento => DateTime.new(1996,8,21),
  :ciudad_nacimiento => "Huizen",
  :posicion => "Medio centro",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,10,11),
  :participaciones => 2,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Karim",
  :apellido => "El Ahmadi",
  :fecha_nacimiento => DateTime.new(1985,1,27),
  :ciudad_nacimiento => "Enschede",
  :posicion => "Medio centro",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  DateTime.new(2004,8,20),
  :participaciones => 48,
  :foto => "lololo",
  :goles => 1,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Nabil",
  :apellido => "Dirar",
  :fecha_nacimiento => DateTime.new(1986,2,25),
  :ciudad_nacimiento => "Tetouan",
  :posicion => "Inferior derecho",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  DateTime.new(2004,11,19),
  :participaciones => 32,
  :foto => "lololo",
  :goles => 3,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Amine",
  :apellido => "Harit",
  :fecha_nacimiento => DateTime.new(1997,6,18),
  :ciudad_nacimiento => "Pontoise",
  :posicion => "Medio centro ofensivo",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  DateTime.new(2016,11,20),
  :participaciones => 2,
  :foto => "lololo",
  :goles => 0,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Hakim",
  :apellido => "Ziyech",
  :fecha_nacimiento => DateTime.new(1993,3,19),
  :ciudad_nacimiento => "Dronten",
  :posicion => "Medio centro ofensivo",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,10,9),
  :participaciones => 13,
  :foto => "lololo",
  :goles => 7,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Younès",
  :apellido => "Belhanda",
  :fecha_nacimiento => DateTime.new(1990,2,25),
  :ciudad_nacimiento => "Aviñón",
  :posicion => "Medio centro ofensivo",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  DateTime.new(2009,4,12),
  :participaciones => 43,
  :foto => "lololo",
  :goles => 3,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Fayçal",
  :apellido => "Fajr",
  :fecha_nacimiento => DateTime.new(1988,8,1),
  :ciudad_nacimiento => "Rouen",
  :posicion => "Medio centro ofensivo",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,11,15),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 1,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Moubarak",
  :apellido => "Boussoufa",
  :fecha_nacimiento => DateTime.new(1985,8,15),
  :ciudad_nacimiento => "Ámsterdam",
  :posicion => "Medio centro ofensivo",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  DateTime.new(2006,5,23),
  :participaciones => 39,
  :foto => "lololo",
  :goles => 5,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Mehdi",
  :apellido => "Carcela-González",
  :fecha_nacimiento => DateTime.new(1989,7,1),
  :ciudad_nacimiento => "Lieja",
  :posicion => "Extremo derecho",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  DateTime.new(2008,5,20),
  :participaciones => 19,
  :foto => "lololo",
  :goles => 1,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Nordin",
  :apellido => "Amrabat",
  :fecha_nacimiento => DateTime.new(1987,3,31),
  :ciudad_nacimiento => "Naarden",
  :posicion => "Extremo derecho",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  DateTime.new(2006,9,10),
  :participaciones => 41,
  :foto => "lololo",
  :goles => 4,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Youssef",
  :apellido => "En-Nesyri",
  :fecha_nacimiento => DateTime.new(1997,6,1),
  :ciudad_nacimiento => "Fez",
  :posicion => "Delantero centro",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  DateTime.new(2016,8,31),
  :participaciones => 15,
  :foto => "lololo",
  :goles => 1,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ayoub",
  :apellido => "El Kaabi",
  :fecha_nacimiento => DateTime.new(1993,6,25),
  :ciudad_nacimiento => "Casablanca",
  :posicion => "Delantero centro",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  DateTime.new(2016,9,21),
  :participaciones => 8,
  :foto => "lololo",
  :goles => 10,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Khalid",
  :apellido => "Boutaïb",
  :fecha_nacimiento => DateTime.new(1987,4,24),
  :ciudad_nacimiento => "Bagnols-sur-Cèze",
  :posicion => "Delantero centro",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  DateTime.new(2006,3,12),
  :participaciones => 15,
  :foto => "lololo",
  :goles => 7,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Aziz",
  :apellido => "Bouhaddouz",
  :fecha_nacimiento => DateTime.new(1987,3,30),
  :ciudad_nacimiento => "Berkan",
  :posicion => "Delantero centro",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  DateTime.new(2006,6,12),
  :participaciones => 14,
  :foto => "lololo",
  :goles => 3,
  :country_id => marruecos.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
