# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
mex = Country.create(
  :nombre => 'México', 
  :apodo => 'El Tri', 
  :grupo => 'F', 
  :escudo => 'public/countries/MexLo.png', 
  :bandera => '../assets/banderas/mexico')

@mexG = mex

  mex_coa = Coach.create(#Mexico 
  :nombre => "Juan Carlos",
  :apellido => "Osorio",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1961,6,8),
  :ciudad_nacimiento => "Santa Rosa de Cabal")

 CoachTeam.create(
  :debut => Date.new(2015,10,14),
  :coach_id => mex_coa.id,
  :country_id  => mex.id)

Player.create([{#México
  :nombre => "Jesús",
  :apellido => "Corona",
  :fecha_nacimiento => Date.new(1981,01,26),
  :ciudad_nacimiento => "Guadalajara",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "Chuy",
  :debut =>  Date.new(2005,4,27),
  :participaciones => 50,
  :foto => "Picture",
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)

},
{
:nombre => "Alfredo",
  :apellido => "Talavera",
  :fecha_nacimiento => Date.new(1982,9,18),
  :ciudad_nacimiento => "La Barca",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "Calaca",
  :debut =>  Date.new(2011,3,26),
  :participaciones => 28,
  :foto => "Picture",
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Guillermo",
  :apellido => "Ochoa",
  :fecha_nacimiento => Date.new(1985,7,13),
  :ciudad_nacimiento => "Guadalajara",
  :posicion => "Portero",
  :dorsal => 13,
  :apodo => "Memo",
  :debut =>  Date.new(2005,12,14),
  :participaciones => 91,
  :foto => "Picture",
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Hugo",
  :apellido => "Ayala",
  :fecha_nacimiento => Date.new(1987,3,31),
  :ciudad_nacimiento => "Zacapu",
  :posicion => "Defensa",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2009,3,11),
  :participaciones => 36,
  :foto => "Picture",
  :goles => 1,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Carlos",
  :apellido => "Salcedo",
  :fecha_nacimiento => Date.new(1993,9,29),
  :ciudad_nacimiento => "Guadalajara",
  :posicion => "Defensa",
  :dorsal => 3,
  :apodo => "Titán",
  :debut =>  Date.new(2015,4,15),
  :participaciones => 20,
  :foto => "Picture",
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Rafael",
  :apellido => "Márquez",
  :fecha_nacimiento => Date.new(1979,2,13),
  :ciudad_nacimiento => "Zamora",
  :posicion => "Defensa",
  :dorsal => 4,
  :apodo => "Rafa",
  :debut =>  Date.new(1997,2,5),
  :participaciones => 143,
  :foto => "Picture",
  :goles => 17,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Diego",
  :apellido => "Reyes",
  :fecha_nacimiento => Date.new(1992,9,19),
  :ciudad_nacimiento => "Ciudad de México",
  :posicion => "Defensa",
  :dorsal => 5,
  :apodo => "Flaco",
  :debut =>  Date.new(2011,7,5),
  :participaciones => 54,
  :foto => "Picture",
  :goles => 1,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Miguel",
  :apellido => "Layún",
  :fecha_nacimiento => Date.new(1988,6,25),
  :ciudad_nacimiento => "Córdoba",
  :posicion => "Defensa",
  :dorsal => 7,
  :apodo => "Expreso de Córdoba",
  :debut =>  Date.new(2013,7,11),
  :participaciones => 62,
  :foto => "Picture",
  :goles => 6,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Héctor",
  :apellido => "Moreno",
  :fecha_nacimiento => Date.new(1988,1,17),
  :ciudad_nacimiento => "Culiacán",
  :posicion => "Defensa",
  :dorsal => 15,
  :apodo => "El Cachi",
  :debut =>  Date.new(2007,10,17),
  :participaciones => 91,
  :foto => "Picture",
  :goles => 3,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Edson",
  :apellido => "Álvarez",
  :fecha_nacimiento => Date.new(1997,10,24),
  :ciudad_nacimiento => "Tlalnepantla",
  :posicion => "Defensa",
  :dorsal => 21,
  :apodo => "Machín",
  :debut =>  Date.new(2017,2,8),
  :participaciones => 10,
  :goles => 1,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Jonathan",
  :apellido => "dos Santos",
  :fecha_nacimiento => Date.new(1990,4,26),
  :ciudad_nacimiento => "Ciudad de México",
  :posicion => "Mediocampista",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2009,9,30),
  :participaciones => 33,
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Marco",
  :apellido => "Fabián",
  :fecha_nacimiento => Date.new(1989,6,21),
  :ciudad_nacimiento => "Guadalajara",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "Marquito",
  :debut =>  Date.new(2012,1,25),
  :participaciones => 36,
  :goles => 9,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Héctor",
  :apellido => "Herrera",
  :fecha_nacimiento => Date.new(1990,4,19),
  :ciudad_nacimiento => "Rosarito",
  :posicion => "Mediocampista",
  :dorsal => 16,
  :apodo => "Zorro",
  :debut =>  Date.new(2012,10,16),
  :participaciones => 65,
  :goles => 5,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Andrés",
  :apellido => "Guardado",
  :fecha_nacimiento => Date.new(1986,9,28),
  :ciudad_nacimiento => "Guadalajara",
  :posicion => "Mediocampista",
  :dorsal => 18,
  :apodo => "Principito",
  :debut =>  Date.new(2005,12,14),
  :participaciones => 145,
  :goles => 24,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Giovani",
  :apellido => "dos Santos",
  :fecha_nacimiento => Date.new(1989,5,11),
  :ciudad_nacimiento => "Ciudad de México",
  :posicion => "Mediocampista",
  :dorsal => 10,
  :apodo => "Gio",
  :debut =>  Date.new(2007,9,9),
  :participaciones => 103,
  :goles => 20,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Raúl",
  :apellido => "Jiménez",
  :fecha_nacimiento => Date.new(1991,5,5),
  :ciudad_nacimiento => "Tepeji del Río",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2013,1,30),
  :participaciones => 62,
  :goles => 14,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Carlos",
  :apellido => "Vela",
  :fecha_nacimiento => Date.new(1989,3,1),
  :ciudad_nacimiento => "Cancún",
  :posicion => "Delantero",
  :dorsal => 11,
  :apodo => "Hiena",
  :debut =>  Date.new(2007,11,12),
  :participaciones => 68,
  :goles => 18,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Jesús Manuel",
  :apellido => "Corona",
  :fecha_nacimiento => Date.new(1993,1,6),
  :ciudad_nacimiento => "Hermosillo",
  :posicion => "Delantero",
  :dorsal => 17,
  :apodo => "Tecatito",
  :debut =>  Date.new(2014,11,12),
  :participaciones => 35,
  :goles => 7,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Oribe",
  :apellido => "Peralta",
  :fecha_nacimiento => Date.new(1984,1,12),
  :ciudad_nacimiento => "Torreón",
  :posicion => "Delantero",
  :dorsal => 19,
  :apodo => "Hermoso",
  :debut =>  Date.new(2005,3,9),
  :participaciones => 66,
  :goles => 26,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Javier",
  :apellido => "Aquino",
  :fecha_nacimiento => Date.new(1990,2,11),
  :ciudad_nacimiento => "San Francisco Ixhuatán",
  :posicion => "Delantero",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2011,7,4),
  :participaciones => 54,
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Hirving",
  :apellido => "Lozano",
  :fecha_nacimiento => Date.new(1995,7,30),
  :ciudad_nacimiento => "Ciudad de México",
  :posicion => "Delantero",
  :dorsal => 22,
  :apodo => "Chucky",
  :debut =>  Date.new(2016,2,10),
  :participaciones => 27,
  :goles => 7,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Jesús",
  :apellido => "Gallardo",
  :fecha_nacimiento => Date.new(1994,8,15),
  :ciudad_nacimiento => "Heroica Cárdenas",
  :posicion => "Delantero",
  :dorsal => 23,
  :apodo => "Gallardo",
  :debut =>  Date.new(2016,10,8),
  :participaciones => 21,
  :goles => 0,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Javier",
  :apellido => "Hernández",
  :fecha_nacimiento => Date.new(1988,6,1),
  :ciudad_nacimiento => "Guadalajara",
  :posicion => "Delantero",
  :dorsal => 14,
  :apodo => "Chicharito",
  :debut =>  Date.new(2009,9,30),
  :participaciones => 101,
  :goles => 49,
  :country_id => mex.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
}])