
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
# movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# Character.create(name: 'Luke', movie: movies.first)
nig = Country.create(
        :nombre => 'Nigeria', 
        :apodo => 'Las Águilas Verdes', 
        :grupo => 'D',
        :escudo => 'public/countries/NigLo.png', 
        :bandera => '../assets/banderas/nigeria')

@nigG = nig

nig_coa = Coach.create(#Nigeria
  :nombre => "Salisu",
  :apellido => "Yusuf",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1962,1,1),
  :ciudad_nacimiento => "Zaria")

CoachTeam.create(
  :debut => Date.new(2016,7,19),
  :coach_id => nig_coa.id,
  :country_id  => nig.id)


Player.create([{#Nigeria
        :nombre => "Daniel ",
        :apellido => "Akpeyi",
        :fecha_nacimiento => Date.new(1986,8,3),
        :ciudad_nacimiento => "Nnewi",
        :posicion => "Portero",
        :dorsal => 16,
        :apodo => "N/A",
        :debut => Date.new(2015,3,29),
        :participaciones => 7,
        :country_id => nig.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
                { 
                :nombre => "Francis",
                :apellido => "Uzoho",
                :fecha_nacimiento => Date.new(1998,10,28),
                :ciudad_nacimiento => "Nwangele",
                :posicion => "Portero",
                :dorsal => 23,
                :apodo => "N/A",
                :debut => Date.new(2017,11,14),
                :participaciones => 3,
                :country_id => nig.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
                {
                :nombre => "Ikechukwu",
                :apellido => "Ezenwa",
                :fecha_nacimiento => Date.new(1988,10,16),
                :ciudad_nacimiento => "Yenagoa",
                :posicion => "Portero",
                :dorsal => 1,
                :apodo => "N/A",
                :debut => Date.new(2015,9,8),
                :participaciones => 24,
                :country_id => nig.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
                {
                :nombre => "Chidozie",
                :apellido => "Awaziem",
                :fecha_nacimiento => Date.new(1997,1,1),
                :ciudad_nacimiento => "Enugu",
                :posicion => "Defensa Central",
                :dorsal => 20,
                :apodo => "N/A",
                :debut => Date.new(2017,6,10),
                :participaciones => 4,
                :country_id => nig.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
                {
                :nombre => "Leon",
                :apellido => "Balogun",
                :fecha_nacimiento => Date.new(1988,6,28),
                :ciudad_nacimiento => "Berlin",
                :posicion => "Defensa Central",
                :dorsal => 6,
                :apodo => "N/A",
                :debut => Date.new(2014,3,6),
                :participaciones => 16,
                :country_id => nig.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{
                :nombre => "Kenneth",
                :apellido => "Omeruo",
                :fecha_nacimiento => Date.new(1993,10,17),
                :ciudad_nacimiento => "Kaduna",
                :posicion => "Defensa Central",
                :dorsal => 22,
                :apodo => "N/A",
                :debut => Date.new(2013,1,9),
                :participaciones => 37,
                :country_id => nig.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{
                :nombre => "William",
                :apellido => "Troost-Ekong",
                :fecha_nacimiento => Date.new(1993,9,1), 
                :ciudad_nacimiento => "Haarlem",
                :posicion => "Defensa Central",
                :dorsal => 5,
                :apodo => "N/A",
                :debut => Date.new(2015,6,13),
                :participaciones => 19,
                :country_id => nig.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{ 

                :nombre => "Elderson",
                :apellido => "Nig",
                :fecha_nacimiento => Date.new(1988,1,20),
                :ciudad_nacimiento => "Benin City",
                :posicion => "Lateral izquierdo",
                :dorsal => 3,
                :apodo => "N/A",
                :debut => Date.new(2010,1,6),
                :participaciones => 60,
                :country_id => nig.id,
                :goles => 3,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{ 
        :nombre => "Bryan",
        :apellido => "Idowu",
        :fecha_nacimiento => Date.new(1992,5,18),
        :ciudad_nacimiento => "St. Petersburg",
        :posicion => "Lateral Derecho",
        :dorsal => 2,
        :apodo => "N/A",
        :debut => Date.new(2017,11,14),
        :participaciones => 3,
        :country_id => nig.id,
        :goles => 1,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Tyronne",
        :apellido => "Ebuehi",
        :fecha_nacimiento => Date.new(1995,12,16),
        :ciudad_nacimiento => "Haarlem",
        :posicion => "Lateral Derecho",
        :dorsal => 21,
        :apodo => "N/A",
        :debut => Date.new(2017,11,14),
        :participaciones => 4,
        :country_id => nig.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 

        :nombre => "Wilfred",
        :apellido => "Ndidi",
        :fecha_nacimiento => Date.new(1996,12,16),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Pivote",
        :dorsal => 4,
        :apodo => "N/A",
        :debut => Date.new(2015,10,8),
        :participaciones => 16,
        :country_id => nig.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 


        :nombre => "John Mikel",
        :apellido => "Obi",
        :fecha_nacimiento => Date.new(1987,4,22),
        :ciudad_nacimiento => "Jos",
        :posicion => "Pivote",
        :dorsal => 10,
        :apodo => "N/A",
        :debut => Date.new(2005,8,17),
        :participaciones => 83,
        :country_id => nig.id,
        :goles => 6,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{

        :nombre => "Ogenyi",
        :apellido => "Onazi",
        :fecha_nacimiento => Date.new(1992,12,25),
        :ciudad_nacimiento => "Benue",
        :posicion => "Pivote",
        :dorsal => 17,
        :apodo => "N/A",
        :debut => Date.new(2012,10,13),
        :participaciones => 50,
        :country_id => nig.id,
        :goles => 1,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 

        :nombre => "Abdullahi",
        :apellido => "Shehu",
        :fecha_nacimiento => Date.new(1993,3,12),
        :ciudad_nacimiento => "Kano",
        :posicion => "Pivote",
        :dorsal => 12,
        :apodo => "N/A",
        :debut => Date.new(2014,1,11),
        :participaciones => 22,
        :country_id => nig.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 
        :nombre => "Joel",
        :apellido => "Obi",
        :fecha_nacimiento => Date.new(1991,5,22),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Medio Centro",
        :dorsal => 15,
        :apodo => "N/A",
        :debut => Date.new(2011,2,9),
        :participaciones => 15,
        :country_id => nig.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "John",
        :apellido => "Ogu",
        :fecha_nacimiento => Date.new(1983,8,20),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Medio centro",
        :dorsal => 19,
        :apodo => "N/A",
        :debut => Date.new(2013,3,23),
        :participaciones => 18,
        :country_id => nig.id,
        :goles => 2,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 
        :nombre => "Victor",
        :apellido => "Moses",
        :fecha_nacimiento => Date.new(1990,12,12),
        :ciudad_nacimiento => "Kaduna",
        :posicion => "Interior derecho",
        :dorsal => 11,
        :apodo => "N/A",
        :debut => Date.new(2012,2,29),
        :participaciones => 32,
        :country_id => nig.id,
        :goles => 11,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 
        :nombre => "Oghenekaro",
        :apellido => "Etebo",
        :fecha_nacimiento => Date.new(1995,11,9),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Medio centro ofensivo",
        :dorsal => 8,
        :apodo => "N/A",
        :debut => Date.new(2013,7,6),
        :participaciones => 12,
        :country_id => nig.id,
        :goles => 1,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 
        :nombre => "Alex",
        :apellido => "Iwobi",
        :fecha_nacimiento => Date.new(1996,5,3),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Extremo izquierdo",
        :dorsal => 18,
        :apodo => "N/A",
        :debut => Date.new(2015,10,8),
        :participaciones => 16,
        :country_id => nig.id,
        :goles => 4,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Ahmed",
        :apellido => "Musa",
        :fecha_nacimiento => Date.new(1992,10,14),
        :ciudad_nacimiento => "Jos",
        :posicion => "Delantero centro",
        :dorsal => 7,
        :apodo => "N/A",
        :debut => Date.new(2010,9,5),
        :participaciones => 69,
        :country_id => nig.id,
        :goles => 13,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Kelechi",
        :apellido => "Iheanacho",
        :fecha_nacimiento => Date.new(1996,10,3),
        :ciudad_nacimiento => "Imo",
        :posicion => "Delantero centro",
        :dorsal => 14,
        :apodo => "N/A",
        :debut => Date.new(2015,11,13),
        :participaciones => 15,
        :country_id => nig.id,
        :goles => 8,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 
        :nombre => "Odion",
        :apellido => "Ighalo",
        :fecha_nacimiento => Date.new(1989,6,16),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Delantero Centro",
        :dorsal => 9,
        :apodo => "N/A",
        :debut => Date.new(2013,3,22),
        :participaciones => 17,
        :country_id => nig.id,
        :goles => 4,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{

        :nombre => "Simy",
        :apellido => "Nig",
        :fecha_nacimiento => Date.new(1992,5,7),
        :ciudad_nacimiento => "Lagos",
        :posicion => "Delantero Centro",
        :dorsal => 13,
        :apodo => "N/A",
        :debut => Date.new(2018,6,16),
        :participaciones => 0,
        :country_id => nig.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
}])
