
pan = Country.create(
  :nombre => 'Panama',
  :apodo => 'Los Canaleros',
  :grupo => 'G',
  :escudo => 'public/countries/PanLo.png',
  :bandera => '../assets/banderas/panama')

@panG = pan

pan_coa = Coach.create(#Panama
  :nombre => "Hernán Darío",
  :apellido => "Gómez",
  :apodo => "El Bolillo",
  :fecha_nacimiento => DateTime.new(1956,2,3),
  :ciudad_nacimiento => "Medellín")

CoachTeam.create(
  :debut => Date.new(2017,7,4),
  :coach_id => pan_coa.id,
  :country_id  => pan.id)

Player.create([{ #Panama
  :nombre => "Jaime",
  :apellido => "Penedo",
  :fecha_nacimiento => Date.new(1981,9,26),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  DateTime.new(2016,7,4),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "José",
  :apellido => "Calderón",
  :fecha_nacimiento => Date.new(1985,8,14),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,7),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Álex",
  :apellido => "Rodríguez",
  :fecha_nacimiento => Date.new(1990,8,5),
  :ciudad_nacimiento => "Panama City",
  :posicion => "Portero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,1,7),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Román",
  :apellido => "Torres",
  :fecha_nacimiento => Date.new(1986,3,20),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Defensa central",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,8,12),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Adolfo",
  :apellido => "Machado",
  :fecha_nacimiento => Date.new(1985,2,14),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Defensa central",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,1,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Hárold",
  :apellido => "Cummings",
  :fecha_nacimiento => Date.new(1992,3,1),
  :ciudad_nacimiento => "Panamá City",
  :posicion => "Defensa central",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,1,7),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Fidel",
  :apellido => "Escobar",
  :fecha_nacimiento => Date.new(1995,1,9),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Defensa central",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,7,27),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Felipe",
  :apellido => "Baloy",
  :fecha_nacimiento => Date.new(1981,2,24),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Defensa central",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,7,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Luis",
  :apellido => "Ovalle",
  :fecha_nacimiento => Date.new(1988,9,7),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Defensa - Lateral izquierdo",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,16),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Éric",
  :apellido => "Davis",
  :fecha_nacimiento => Date.new(1991,3,31),
  :ciudad_nacimiento => "Colón",
  :posicion => "Defensa - Lateral izquierdo",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,9,11),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Michael",
  :apellido => "Murillo",
  :fecha_nacimiento => Date.new(1996,2,11),
  :ciudad_nacimiento => "Panama City",
  :posicion => "Defensa - Lateral derecho",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Aníbal",
  :apellido => "Godoy",
  :fecha_nacimiento => Date.new(1996,2,11),
  :ciudad_nacimiento => "Panama City",
  :posicion => "Medio campo",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  DateTime.new(2015,8,6),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Gabriel",
  :apellido => "Gómez",
  :fecha_nacimiento => Date.new(1996,2,11),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Medio campo",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,1,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ricardo",
  :apellido => "Ávila",
  :fecha_nacimiento => Date.new(1996,2,11),
  :ciudad_nacimiento => "Panama City",
  :posicion => "Medio campo",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,7,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Armando",
  :apellido => "Cooper",
  :fecha_nacimiento => Date.new(1987,11,26),
  :ciudad_nacimiento => "Colón",
  :posicion => "Medio campo",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,29),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "José",
  :apellido => "Rodríguez",
  :fecha_nacimiento => Date.new(1998,6,19),
  :ciudad_nacimiento => "Panama City",
  :posicion => "Medio campo",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,1,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Yoel",
  :apellido => "Bárcenas",
  :fecha_nacimiento => Date.new(1993,10,23),
  :ciudad_nacimiento => "Colón",
  :posicion => "Medio campo",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,1,24),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ismael",
  :apellido => "Díaz",
  :fecha_nacimiento => Date.new(1997,5,12),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Delantero",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,9,22),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Valentín",
  :apellido => "Pimentel",
  :fecha_nacimiento => Date.new(1991,5,30),
  :ciudad_nacimiento => "Panama-City",
  :posicion => "Delantero",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,1,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Gabriel",
  :apellido => "Torres",
  :fecha_nacimiento => Date.new(1991,5,30),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,22),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Abdiel",
  :apellido => "Arroyo",
  :fecha_nacimiento => Date.new(1991,5,30),
  :ciudad_nacimiento => "Colón",
  :posicion => "Delantero",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,22),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Luis",
  :apellido => "Tejada",
  :fecha_nacimiento => Date.new(1982,3,28),
  :ciudad_nacimiento => "Panama-Stadt",
  :posicion => "Delantero",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  DateTime.new(2018,1,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Blas",
  :apellido => "Pérez",
  :fecha_nacimiento => Date.new(1982,3,28),
  :ciudad_nacimiento => "Panama-City",
  :posicion => "Delantero",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  DateTime.new(2017,7,1),
  :participaciones => 1,
  :country_id => pan.id,
  :goles => 0,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
