# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first


peru = Country.create(
  :nombre => 'Peru', 
  :apodo => 'Los Incas', 
  :grupo => 'C', 
  :escudo => 'public/countries/PerLo.png', 
  :bandera => '../assets/banderas/peru')

@peruG = peru

peru_coa = Coach.create(#Peru
  :nombre => "Ricardo",
  :apellido => "Gareca",
  :apodo => "El Flaco",
  :fecha_nacimiento => Date.new(1958,2,10),
  :ciudad_nacimiento => "Tapiales")

CoachTeam.create(
  :debut => Date.new(2015,2,9),
  :coach_id => peru_coa.id,
  :country_id  => peru.id)

Player.create([{ #Peru
  :nombre => "Pedro",
  :apellido => "Gallese",
  :fecha_nacimiento => Date.new(1990,4,23),
  :ciudad_nacimiento => "Lima",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2014,8,7),
  :participaciones => 37,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Carlos",
  :apellido => "Caceda",
  :fecha_nacimiento => Date.new(1991,9,27),
  :ciudad_nacimiento => "Lima",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2016,5,29),
  :participaciones => 6,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Jose",
  :apellido => "Carvallo",
  :fecha_nacimiento => Date.new(1986,3,1),
  :ciudad_nacimiento => "Lima",
  :posicion => "Portero",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2007,9,12),
  :participaciones => 5,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Alberto",
  :apellido => "Rodriguez",
  :fecha_nacimiento => Date.new(1984,3,31),
  :ciudad_nacimiento => "Lima",
  :posicion => "Defensa",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2003,4,3),
  :participaciones => 73,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Aldo",
  :apellido => "Corzo",
  :fecha_nacimiento => Date.new(1989,5,20),
  :ciudad_nacimiento => "Lima",
  :posicion => "Defensa",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2009,2,6),
  :participaciones => 24,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Anderson",
  :apellido => "Santamaria",
  :fecha_nacimiento => Date.new(1992,1,10),
  :ciudad_nacimiento => "Tingo Maria",
  :posicion => "Defensa",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,14),
  :participaciones => 4,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Miguel",
  :apellido => "Araujo",
  :fecha_nacimiento => Date.new(1994,10,24),
  :ciudad_nacimiento => "Lima",
  :posicion => "Defensa",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,19),
  :participaciones => 7,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Miguel",
  :apellido => "Trauco",
  :fecha_nacimiento => Date.new(1993,7,3),
  :ciudad_nacimiento => "Tarapoto",
  :posicion => "Defensa",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2014,8,7),
  :participaciones => 3,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Christian",
  :apellido => "Ramos",
  :fecha_nacimiento => Date.new(1988,11,4),
  :ciudad_nacimiento => "Lima",
  :posicion => "Defensa",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2009,9,10),
  :participaciones => 67,
  :goles => 3,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Luis",
  :apellido => "Advincula",
  :fecha_nacimiento => Date.new(1990,3,2),
  :ciudad_nacimiento => "Chincha",
  :posicion => "Defensa",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2010,9,4),
  :participaciones => 64,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Nilson",
  :apellido => "Loyola",
  :fecha_nacimiento => Date.new(1994,10,26),
  :ciudad_nacimiento => "Lima",
  :posicion => "Defensa",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2016,11,11),
  :participaciones => 3,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Paolo",
  :apellido => "Hurtado",
  :fecha_nacimiento => Date.new(1990,7,27),
  :ciudad_nacimiento => "Callao",
  :posicion => "Mediocampista",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2011,9,3),
  :participaciones => 31,
  :goles => 3,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Christian",
  :apellido => "Cueva",
  :fecha_nacimiento => Date.new(1991,11,23),
  :ciudad_nacimiento => "Trujillo",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2011,6,1),
  :participaciones => 47,
  :goles => 7,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Renato",
  :apellido => "Tapia",
  :fecha_nacimiento => Date.new(1995,7,28),
  :ciudad_nacimiento => "Lima",
  :posicion => "Mediocampista",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  Date.new(2015,4,1),
  :participaciones => 29,
  :goles => 3,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Andy",
  :apellido => "Polo",
  :fecha_nacimiento => Date.new(1994,9,29),
  :ciudad_nacimiento => "Lima",
  :posicion => "Mediocampista",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2016,3,30),
  :participaciones => 15,
  :goles => 1,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Wilder",
  :apellido => "Cartagena",
  :fecha_nacimiento => Date.new(1994,9,23),
  :ciudad_nacimiento => "Lima",
  :posicion => "Mediocampista",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2017,9,5),
  :participaciones => 3,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Yoshimar",
  :apellido => "Yotun",
  :fecha_nacimiento => Date.new(1990,5,7),
  :ciudad_nacimiento => "Lima",
  :posicion => "Mediocampista",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2012,5,25),
  :participaciones => 70,
  :goles => 2,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Pedro",
  :apellido => "Aquino",
  :fecha_nacimiento => Date.new(1995,4,13),
  :ciudad_nacimiento => "Lima",
  :posicion => "Mediocampista",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2016,9,1),
  :participaciones => 11,
  :goles => 0,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Paolo",
  :apellido => "Guerrero",
  :fecha_nacimiento => Date.new(1984,1,1),
  :ciudad_nacimiento => "Lima",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2004,10,9),
  :participaciones => 87,
  :goles => 33,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Jefferson",
  :apellido => "Farfan",
  :fecha_nacimiento => Date.new(1984,10,26),
  :ciudad_nacimiento => "Lima",
  :posicion => "Delantero",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2003,2,23),
  :participaciones => 81,
  :goles => 24,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Raul",
  :apellido => "Ruidiaz",
  :fecha_nacimiento => Date.new(1990,7,25),
  :ciudad_nacimiento => "Lima",
  :posicion => "Delantero",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2011,6,1),
  :participaciones => 29,
  :goles => 4,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Andre",
  :apellido => "Carrillo",
  :fecha_nacimiento => Date.new(1991,6,14),
  :ciudad_nacimiento => "Lima",
  :posicion => "Delantero",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  Date.new(2011,7,13),
  :participaciones => 44,
  :goles => 4,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Edison",
  :apellido => "Flores",
  :fecha_nacimiento => Date.new(1994,5,14),
  :ciudad_nacimiento => "Lima",
  :posicion => "Delantero",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,14),
  :participaciones => 27,
  :goles => 9,
  :country_id => peru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
}])
