# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
# movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# Character.create(name: 'Luke', movie: movies.first)
rus = Country.create(
        :nombre => 'Rusia', 
        :apodo => 'El Equipo Nacional', 
        :grupo => 'A',
        :escudo => 'public/countries/RusLo.png', 
        :bandera => '../assets/banderas/rusia')

@rusG = rus

rus_coa =  Coach.create(#Rusia
  :nombre => "Stanislav",
  :apellido => "Cherchésov",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1963,9,2),
  :ciudad_nacimiento => "Alagir")

CoachTeam.create(
  :debut => Date.new(2016,8,11),
  :coach_id => rus_coa.id,
  :country_id  => rus.id)

Player.create([{#Rusia
        :nombre => "Igor ",
        :apellido => "Akinfeev",
        :fecha_nacimiento => Date.new(1986,4,8),
        :ciudad_nacimiento => "Vidnoe, Moskau Region",
        :posicion => "Portero",
        :dorsal => 1,
        :apodo => "N/A",
        :debut => Date.new(2004,4,28),
        :participaciones => 106,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Andrey",
        :apellido => "Lunev",
        :fecha_nacimiento => Date.new(1991,11,13),
        :ciudad_nacimiento => "Moskau",
        :posicion => "Portero",
        :dorsal => 12,
        :apodo => "N/A",
        :debut => Date.new(2017,10,10),
        :participaciones => 3,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)   
},
{
        :nombre => "Vladimir",
        :apellido => "Gabulov",
        :fecha_nacimiento => Date.new(1983,10,19),
        :ciudad_nacimiento => "Mozdok, Alania Republic",
        :posicion => "Portero",
        :dorsal => 20,
        :apodo => "N/A",
        :debut => Date.new(2007,8,27),
        :participaciones => 10,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
        {
        :nombre => "Andrey",
        :apellido => "Semenov",
        :fecha_nacimiento => Date.new(1983,7,29),
        :ciudad_nacimiento => "Moskau",
        :posicion => "Defensa Central",
        :dorsal => 5,
        :apodo => "N/A",
        :debut => Date.new(2014,5,30),
        :participaciones => 6,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Ilya",
        :apellido => "Kutepov",
        :fecha_nacimiento => Date.new(1993,7,29),
        :ciudad_nacimiento => "Stavropol",
        :posicion => "Defensa Central",
        :dorsal => 3,
        :apodo => "N/A",
        :debut => Date.new(2016,10,9),
        :participaciones => 7,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Vladimir",
        :apellido => "Granat",
        :fecha_nacimiento => Date.new(1987,5,22),
        :ciudad_nacimiento => "Ulan-Ude",
        :posicion => "Defensa Central",
        :dorsal => 14,
        :apodo => "N/A",
        :debut => Date.new(2013,9,6),
        :participaciones => 12,
        :country_id => rus.id,
        :goles => 1,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Sergey",
        :apellido => "Ignashevich",
        :fecha_nacimiento => Date.new(1979,7,14), 
        :ciudad_nacimiento => "Moskau",
        :posicion => "Defensa Central",
        :dorsal => 4,
        :apodo => "N/A",
        :debut => Date.new(2002,8,21),
        :participaciones => 122,
        :country_id => rus.id,
        :goles => 8,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 

        :nombre => "Fedor",
        :apellido => "Kudryashov",
        :fecha_nacimiento => Date.new(1987,4,5),
        :ciudad_nacimiento => "Mamakan, Irkutsk Region",
        :posicion => "Lateral izquierdo",
        :dorsal => 13,
        :apodo => "N/A",
        :debut => Date.new(2016,8,31),
        :participaciones => 19,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{

        :nombre => "Mário",
        :apellido => "Fernandes",
        :fecha_nacimiento => Date.new(1990,9,19),
        :ciudad_nacimiento => "São Caetano do Sul",
        :posicion => "Lateral Derecho",
        :dorsal => 2,
        :apodo => "N/A",
        :debut => Date.new(2017,10,7),
        :participaciones => 4,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Igor",
        :apellido => "Smolnikov",
        :fecha_nacimiento => Date.new(1988,8,8),
        :ciudad_nacimiento => "Kamensk-Uralsk,Ekaterniburg Region",
        :posicion => "Lateral Derecho",
        :dorsal => 23,
        :apodo => "N/A",
        :debut => Date.new(2013,11,19),
        :participaciones => 23,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 

        :nombre => "Aleksandr",
        :apellido => "Golovin",
        :fecha_nacimiento => Date.new(1996,5,30),
        :ciudad_nacimiento => "Kaltan, Kemerovo Region",
        :posicion => "Medio centro",
        :dorsal => 17,
        :apodo => "N/A",
        :debut => Date.new(2015,6,7),
        :participaciones => 19,
        :country_id => rus.id,
        :goles => 2,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{ 

        :nombre => "Alan",
        :apellido => "Dzagoev",
        :fecha_nacimiento => Date.new(1990,6,17),
        :ciudad_nacimiento => "Beslan, Alania Republic",
        :posicion => "Medio centro",
        :dorsal => 9,
        :apodo => "N/A",
        :debut => Date.new(2008,10,11),
        :participaciones => 57,
        :country_id => rus.id,
        :goles => 9,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Roman",
        :apellido => "Zobnin",
        :fecha_nacimiento => Date.new(1994,2,11),
        :ciudad_nacimiento => "Irkutsk",
        :posicion => "Medio Centro",
        :dorsal => 11,
        :apodo => "N/A",
        :debut => Date.new(2015,3,31),
        :participaciones => 12,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Daler",
        :apellido => "Kuzyaev",
        :fecha_nacimiento => Date.new(1993,1,15),
        :ciudad_nacimiento => "Naberezhnye Chelny,Tatarstan Republic",
        :posicion => "Medio Centro",
        :dorsal => 7,
        :apodo => "N/A",
        :debut => Date.new(2017,10,7),
        :participaciones => 6,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
        :nombre => "Yuri",
        :apellido => "Gazinskiy",
        :fecha_nacimiento => Date.new(1989,7,20),
        :ciudad_nacimiento => "Truskolasy",
        :posicion => "Medio Centro",
        :dorsal => 8,
        :apodo => "N/A",
        :debut => Date.new(2016,8,31),
        :participaciones => 6,
        :country_id => rus.id,
        :goles => 0,
        :created_at => Date.new(2018,6.6),
        :updated_at => Date.new(2018,6.6)
},
{
                :nombre => "Yuri",
                :apellido => "Zhirkov",
                :fecha_nacimiento => Date.new(1983,8,20),
                :ciudad_nacimiento => "Tambov",
                :posicion => "Interior izquierdo",
                :dorsal => 13,
                :apodo => "N/A",
                :debut => Date.new(2005,2,9),
                :participaciones => 84,
                :country_id => rus.id,
                :goles => 2,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{ 

                :nombre => "Aleksey",
                :apellido => "Miranchuk",
                :fecha_nacimiento => Date.new(1995,10,17),
                :ciudad_nacimiento => "Slavyansk-na-Kubani, Krasnodar Region",
                :posicion => "Medio centro ofensivo",
                :dorsal => 15,
                :apodo => "N/A",
                :debut => Date.new(2015,6,7),
                :participaciones => 18,
                :country_id => rus.id,
                :goles => 4,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{ 
                :nombre => "Anton",
                :apellido => "Miranchuk",
                :fecha_nacimiento => Date.new(1995,10,17),
                :ciudad_nacimiento => "Slavyansk-na-Kubani, Krasnodar Region",
                :posicion => "Medio centro ofensivo",
                :dorsal => 16,
                :apodo => "N/A",
                :debut => Date.new(2017,10,7),
                :participaciones => 6,
                :country_id => rus.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{ 

                :nombre => "Aleksandr",
                :apellido => "Erokhin",
                :fecha_nacimiento => Date.new(1989,10,13),
                :ciudad_nacimiento => "Barnaul",
                :posicion => "Medio centro ofensivo",
                :dorsal => 21,
                :apodo => "N/A",
                :debut => Date.new(2016,8,31),
                :participaciones => 17,
                :country_id => rus.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{ 

                :nombre => "Denis",
                :apellido => "Cheryshev",
                :fecha_nacimiento => Date.new(1990,12,26),
                :ciudad_nacimiento => "Nizhniy Novgorod",
                :posicion => "Extremo izquierdo",
                :dorsal => 6,
                :apodo => "N/A",
                :debut => Date.new(2012,11,14),
                :participaciones => 11,
                :country_id => rus.id,
                :goles => 0,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{

                :nombre => "Aleksandr",
                :apellido => "Samedov",
                :fecha_nacimiento => Date.new(1984,7,19),
                :ciudad_nacimiento => "Moskau",
                :posicion => "Extremo derecho",
                :dorsal => 19,
                :apodo => "N/A",
                :debut => Date.new(2011,10,7),
                :participaciones => 48,
                :country_id => rus.id,
                :goles => 7,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{
                :nombre => "Fedor",
                :apellido => "Smolov",
                :fecha_nacimiento => Date.new(2012,11,14),
                :ciudad_nacimiento => "Saratov",
                :posicion => "Delantero Centro",
                :dorsal => 10,
                :apodo => "N/A",
                :debut => Date.new(2013,3,22),
                :participaciones => 32,
                :country_id => rus.id,
                :goles => 12,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
},
{
                :nombre => "Artem",
                :apellido => "Dzyuba",
                :fecha_nacimiento => Date.new(1988,8,22),
                :ciudad_nacimiento => "Moskau",
                :posicion => "Delantero Centro",
                :dorsal => 22,
                :apodo => "N/A",
                :debut => Date.new(2011,11,11),
                :participaciones => 23,
                :country_id => rus.id,
                :goles => 11,
                :created_at => Date.new(2018,6.6),
                :updated_at => Date.new(2018,6.6)
}])

