# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
sen = Country.create(
  :nombre => 'Senegal', 
  :apodo => 'Les Lions de la Téranga', 
  :grupo => 'H', 
  :escudo => 'public/countries/SenLo.png', 
  :bandera => '../assets/banderas/senegal')

@senG = sen

sen_coa = Coach.create(#Senegal
  :nombre => "Aliou",
  :apellido => "Cissé",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1976,3,24),
  :ciudad_nacimiento => "Ziguinchor")

 CoachTeam.create(
  :debut => Date.new(2015,3,5),
  :coach_id => sen_coa.id,
  :country_id  => sen.id)

Player.create([{ #Senegal
  :nombre => "Alfred",
  :apellido => "Gomis",
  :fecha_nacimiento => Date.new(1993,9,5),
  :ciudad_nacimiento => "Ziguinchor",
  :posicion => "Portero",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,14),
  :participaciones => 1,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Abdoulaye",
  :apellido => "Diallo",
  :fecha_nacimiento => Date.new(1992,3,30),
  :ciudad_nacimiento => "Reims",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2015,3,28),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Khadim",
  :apellido => "N'Diaye",
  :fecha_nacimiento => Date.new(1995,4,5),
  :ciudad_nacimiento => "Dakar",
  :posicion => "Portero",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2010,5,28),
  :participaciones => 24,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)

},
{
  :nombre => "Kalidou",
  :apellido => "Koulibaly",
  :fecha_nacimiento => Date.new(1991,6,20),
  :ciudad_nacimiento => "Saint-Dié-des-Vosges",
  :posicion => "Defensa",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2015,9,5),
  :participaciones => 23,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Salif",
  :apellido => "Sane",
  :fecha_nacimiento => Date.new(1990,8,25),
  :ciudad_nacimiento => "Lormont",
  :posicion => "Defensa",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,6),
  :participaciones => 19,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Kara",
  :apellido => "",
  :fecha_nacimiento => Date.new(1989,11,11),
  :ciudad_nacimiento => "Diasse",
  :posicion => "Defensa",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2012,9,8),
  :participaciones => 51,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Saliou",
  :apellido => "Ciss",
  :fecha_nacimiento => Date.new(1989,9,15),
  :ciudad_nacimiento => "Dakar",
  :posicion => "Defensa",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2012,11,14),
  :participaciones => 17,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Youssouf",
  :apellido => "Sabaly",
  :fecha_nacimiento => Date.new(1993,3,5),
  :ciudad_nacimiento => "Chesnay",
  :posicion => "Defensa",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,10),
  :participaciones => 3,
  :foto => "lololo",
  :goles => 3,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Lamine",
  :apellido => "Gassama",
  :fecha_nacimiento => Date.new(1989,10,20),
  :ciudad_nacimiento => "Marselle",
  :posicion => "Defensa",
  :dorsal => 89,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,10),
  :participaciones => 34,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Moussa",
  :apellido => "Wagué",
  :fecha_nacimiento => Date.new(1998,10,4),
  :ciudad_nacimiento => "Bignona",
  :posicion => "Defensa",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2017,3,23),
  :participaciones => 8,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Cheikhou",
  :apellido => "Kouyaté",
  :fecha_nacimiento => Date.new(1989,12,21),
  :ciudad_nacimiento => "Dakar",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2012,2,29),
  :participaciones => 46,
  :foto => "lololo",
  :goles => 3,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Alfred",
  :apellido => "N'Diaye",
  :fecha_nacimiento => Date.new(1990,3,6),
  :ciudad_nacimiento => "Paris",
  :posicion => "Mediocampista",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,14),
  :participaciones => 18,
  :foto => "lololo",
  :goles => 1,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Idrissa",
  :apellido => "Gueye",
  :fecha_nacimiento => Date.new(1989,9,26),
  :ciudad_nacimiento => "Dakar",
  :posicion => "Mediocampista",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2011,11,11),
  :participaciones => 18,
  :foto => "lololo",
  :goles => 1,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Badou",
  :apellido => "Ndiaye",
  :fecha_nacimiento => Date.new(1990,10,27),
  :ciudad_nacimiento => "Dakar",
  :posicion => "Mediocampista",
  :dorsal => 27,
  :apodo => "N/A",
  :debut =>  Date.new(2015,9,5),
  :participaciones => 18,
  :foto => "lololo",
  :goles => 1,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Cheikh",
  :apellido => "N'Doye",
  :fecha_nacimiento => Date.new(1986,3,29),
  :ciudad_nacimiento => "Rufisque",
  :posicion => "Mediocampista",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2014,5,31),
  :participaciones => 23,
  :foto => "lololo",
  :goles => 1,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Sadio",
  :apellido => "Mané",
  :fecha_nacimiento => Date.new(1992,4,10),
  :ciudad_nacimiento => "Sedhiou",
  :posicion => "Mediocampista",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2012,5,25),
  :participaciones => 51,
  :foto => "lololo",
  :goles => 14,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Keita",
  :apellido => "Baldé",
  :fecha_nacimiento => Date.new(1995,3,8),
  :ciudad_nacimiento => "Arbùcies",
  :posicion => "Mediocampista",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2012,5,25),
  :participaciones => 16,
  :foto => "lololo",
  :goles => 3,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Ismaila",
  :apellido => "Sarr",
  :fecha_nacimiento => Date.new(1998,2,25),
  :ciudad_nacimiento => "Saint-Louis",
  :posicion => "Mediocampistas",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2017,1,15),
  :participaciones => 13,
  :foto => "lololo",
  :goles => 2,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "M'Baye",
  :apellido => "Niang",
  :fecha_nacimiento => Date.new(1994,12,19),
  :ciudad_nacimiento => "Meulan",
  :posicion => "Delantero",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2017,10,7),
  :participaciones => 4,
  :foto => "lololo",
  :goles => 0,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Moussa",
  :apellido => "Konaté",
  :fecha_nacimiento => Date.new(1993,4,3),
  :ciudad_nacimiento => "Mbour",
  :posicion => "Delantero",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2012,2,29),
  :participaciones => 26,
  :foto => "lololo",
  :goles => 9,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Diafra",
  :apellido => "Sakho",
  :fecha_nacimiento => Date.new(1989,12,24),
  :ciudad_nacimiento => "Guédiawaye",
  :posicion => "Delantero",
  :dorsal => 25,
  :apodo => "N/A",
  :debut =>  Date.new(2014,5,22),
  :participaciones => 9,
  :foto => "lololo",
  :goles => 3,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
},
{
  :nombre => "Moussa",
  :apellido => "Sow",
  :fecha_nacimiento => Date.new(1986,1,19),
  :ciudad_nacimiento => "Mantes-la-Jolie",
  :posicion => "Delantero",
  :dorsal => 99,
  :apodo => "N/A",
  :debut =>  Date.new(2009,8,12),
  :participaciones => 50,
  :foto => "lololo",
  :goles => 18,
  :country_id => sen.id,
  :created_at => Date.new(2018,6,4),
  :updated_at => Date.new(2018,6,4)
}])
