# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ser = Country.create(
  :nombre => 'Serbia', 
  :apodo => 'Águilas Blancas', 
  :grupo => 'E', 
  :escudo => 'public/countries/SerLo.png', 
  :bandera => '../assets/banderas/serbia')

@serG = ser

 ser_coa =  Coach.create(#Serbia
  :nombre => "Mladen",
  :apellido => "Krstajić",
  :apodo => "N/A",
  :fecha_nacimiento => Date.new(1974,3,4),
  :ciudad_nacimiento => "Zenica")

 CoachTeam.create(
  :debut => Date.new(2018,1,29),
  :coach_id => ser_coa.id,
  :country_id  => ser.id)

Player.create([{ #Serbia
  :nombre => "Vladimir",
  :apellido => "Stojkovic",
  :fecha_nacimiento => Date.new(1983,6,28),
  :ciudad_nacimiento => "Loznica",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,16),
  :participaciones => 80,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Antonio",
  :apellido => "Rukavina",
  :fecha_nacimiento => Date.new(1984,1,26),
  :ciudad_nacimiento => "Belgrad",
  :posicion => "Defensa",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2007,6,2),
  :participaciones => 46,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Dusko",
  :apellido => "Tosic",
  :fecha_nacimiento => Date.new(1985,1,19),
  :ciudad_nacimiento => "orlovat",
  :posicion => "Defensa",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2006,11,15),
  :participaciones => 22,
  :goles => 1,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Luka",
  :apellido => "Milivojevic",
  :fecha_nacimiento => Date.new(1991,7,4),
  :ciudad_nacimiento => "Kragujevac",
  :posicion => "Medio campista",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2012,11,14),
  :participaciones => 27,
  :goles => 1,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Uros",
  :apellido => "Spajic",
  :fecha_nacimiento => Date.new(1993,2,13),
  :ciudad_nacimiento => "Belgrad",
  :posicion => "Defensa central",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2015,9,4),
  :participaciones => 5,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Branislav",
  :apellido => "Ivanovic",
  :fecha_nacimiento => Date.new(1984,2,22),
  :ciudad_nacimiento => "Sremska a MItrovica",
  :posicion => "Defensa Central",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2006,8,16),
  :participaciones => 102,
  :goles => 12,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Andrija",
  :apellido => "Zivkovic",
  :fecha_nacimiento => Date.new(1996,7,11),
  :ciudad_nacimiento => "nik",
  :posicion => "Atacante Medio campista",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2013,10,11),
  :participaciones => 10,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Aleksandar",
  :apellido => "Prijovic",
  :fecha_nacimiento => Date.new(1990,4,21),
  :ciudad_nacimiento => "sa.Gallen",
  :posicion => "Centro Delantero",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,11),
  :participaciones => 8,
  :goles => 1,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Aleksadar",
  :apellido => "Mitrovic",
  :fecha_nacimiento => Date.new(1994,9,16),
  :ciudad_nacimiento => "Smederevo",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2013,6,7),
  :participaciones => 36,
  :goles => 13,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Dusan",
  :apellido => "Tadic",
  :fecha_nacimiento => Date.new(1988,11,20),
  :ciudad_nacimiento => "Backa Topola",
  :posicion => "Medio centro ofensivo",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2008,12,14),
  :participaciones => 52,
  :goles => 13,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Aleksandar",
  :apellido => "Kolarov",
  :fecha_nacimiento => Date.new(1985,11,10),
  :ciudad_nacimiento => "Belgrad",
  :posicion => "Lateral izquierdo",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2008,5,28),
  :participaciones => 74,
  :goles => 10,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Predrag",
  :apellido => "Rajkovic",
  :fecha_nacimiento => Date.new(1995,10,31),
  :ciudad_nacimiento => "Negotin",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,14),
  :participaciones => 7,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Milos",
  :apellido => "Veljkovic",
  :fecha_nacimiento => Date.new(1995,9,26),
  :ciudad_nacimiento => "Basel",
  :posicion => "Defensa central",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,10),
  :participaciones => 2,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Milan",
  :apellido => "Rodic",
  :fecha_nacimiento => Date.new(1991,4,2),
  :ciudad_nacimiento => "Drvar",
  :posicion => "Defensa",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2018,6,4),
  :participaciones => 1,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Nikola",
  :apellido => "Milenkovic",
  :fecha_nacimiento => Date.new(1997,10,12),
  :ciudad_nacimiento => "Belgrad",
  :posicion => "Medio campista",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2018,6,4),
  :participaciones => 1,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Marko",
  :apellido => "Grujic",
  :fecha_nacimiento => Date.new(1996,4,13),
  :ciudad_nacimiento => "Belgrad",
  :posicion => "Medio campista",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2016,5,25),
  :participaciones => 7,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Filip",
  :apellido => "Kostic",
  :fecha_nacimiento => Date.new(1992,11,01),
  :ciudad_nacimiento => "kragujevac",
  :posicion => "EXtremo Izquierdo",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2015,6,7),
  :participaciones => 22,
  :goles => 2,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "  Nemanja",
  :apellido => "Radonjic",
  :fecha_nacimiento => Date.new(1996,2,15),
  :ciudad_nacimiento => "Nis",
  :posicion => "Lateral izquierdo",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,14),
  :participaciones => 2,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Luka",
  :apellido => "Jovic",
  :fecha_nacimiento => Date.new(1997,12,23),
  :ciudad_nacimiento => "Bijeljina",
  :posicion => "Delantero centro",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2018,6,4),
  :participaciones => 1,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Milinkovic",
  :apellido => "Savic",
  :fecha_nacimiento => Date.new(1995,2,27),
  :ciudad_nacimiento => "Lleida",
  :posicion => "Medio campista",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,10),
  :participaciones => 3,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Nemanja",
  :apellido => "Matic",
  :fecha_nacimiento => Date.new(1988,8,1),
  :ciudad_nacimiento => "Sabac",
  :posicion => "Medio campista",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2008,12,14),
  :participaciones => 39,
  :goles => 2,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Adem",
  :apellido => "Ljajic",
  :fecha_nacimiento => Date.new(1991,9,29),
  :ciudad_nacimiento => "Novi Pazar",
  :posicion => "Medio centro ofensivo",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2010,11,17),
  :participaciones => 28,
  :goles => 5,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
},
{
  :nombre => "Marko",
  :apellido => "Dmitrovic",
  :fecha_nacimiento => Date.new(1992,1,24),
  :ciudad_nacimiento => "Subotica",
  :posicion => "Portero",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,14),
  :participaciones => 2,
  :goles => 0,
  :country_id => ser.id,
  :created_at => Date.new(2018,6,7),
  :updated_at => Date.new(2018,6,7)
}])
