# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first

sui = Country.create(
  :nombre => 'Suiza', 
  :apodo => 'Schweizer Nati',
  :grupo => 'E', 
  :escudo => 'public/countries/SuiLo.png', 
  :bandera => '../assets/banderas/suiza')

@suiG = sui

 sui_coa =   Coach.create(#Suiza
  :nombre => "Vladimir",
  :apellido => "Petković",
  :apodo => "Il Dottore",
  :fecha_nacimiento => Date.new(1963,8,15),
  :ciudad_nacimiento => "Sarajevo")

 CoachTeam.create(
  :debut => Date.new(2014,8,1),
  :coach_id => sui_coa.id,
  :country_id => sui.id)

Player.create([{ #Suiza
  :nombre => "Yann",
  :apellido => "Sommer",
  :fecha_nacimiento => Date.new(1988,12,17),
  :ciudad_nacimiento => "Morges",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "N/A",
  :debut =>  Date.new(2012,5,30),
  :participaciones => 34,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Stephan",
  :apellido => "Lichtsteiner",
  :fecha_nacimiento => Date.new(1984,1,16),
  :ciudad_nacimiento => "Adligenswil",
  :posicion => "Defensa",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2006,11,15),
  :participaciones => 98,
  :goles => 8,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "François",
  :apellido => "Moubandje",
  :fecha_nacimiento => Date.new(1990,6,21),
  :ciudad_nacimiento => "Duala-Suiza",
  :posicion => "Defensa",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,15),
  :participaciones => 16,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Nico",
  :apellido => "Elvedi",
  :fecha_nacimiento => Date.new(1996,9,30),
  :ciudad_nacimiento => "Zürich",
  :posicion => "Defensa",
  :dorsal => 4,
  :apodo => "N/A",
  :debut =>  Date.new(2016,5,28),
  :participaciones => 5,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Manuel",
  :apellido => "Akanji",
  :fecha_nacimiento => Date.new(1995,7,19),
  :ciudad_nacimiento => "Neftenbach ZH",
  :posicion => "Defensa",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,9),
  :participaciones => 5,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Michael",
  :apellido => "Lang",
  :fecha_nacimiento => Date.new(1991,2,8),
  :ciudad_nacimiento => "Diasse",
  :posicion => "Defensa",
  :dorsal => 6,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,14),
  :participaciones => 23,
  :goles => 2,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Breel",
  :apellido => "Embolo",
  :fecha_nacimiento => Date.new(1997,2,14),
  :ciudad_nacimiento => "Yaoundé-Senegal",
  :posicion => "Delantero",
  :dorsal => 7,
  :apodo => "N/A",
  :debut =>  Date.new(2015,3,31),
  :participaciones => 23,
  :goles => 3,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Remo",
  :apellido => "Freuler",
  :fecha_nacimiento => Date.new(1992,4,15),
  :ciudad_nacimiento => "Ennenda",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "N/A",
  :debut =>  Date.new(2017,6,1),
  :participaciones => 9,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Haris",
  :apellido => "SEFEROVIC",
  :fecha_nacimiento => Date.new(1989,10,20),
  :ciudad_nacimiento => "Sursee - Bosnia",
  :posicion => "Mediocampista",
  :dorsal => 9,
  :apodo => "N/A",
  :debut =>  Date.new(2017,11,10),
  :participaciones => 12,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Granit",
  :apellido => "XHAKA",
  :fecha_nacimiento => Date.new(1992,9,27),
  :ciudad_nacimiento => "Basel",
  :posicion => "Mediocampista",
  :dorsal => 10,
  :apodo => "N/A",
  :debut =>  Date.new(2011,6,4),
  :participaciones => 61,
  :goles => 9,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Valon",
  :apellido => "Behrami",
  :fecha_nacimiento => Date.new(1985,4,19),
  :ciudad_nacimiento => "Mitrovicë - Kosovo",
  :posicion => "Mediocampista",
  :dorsal => 11,
  :apodo => "N/A",
  :debut =>  Date.new(2005,10,8),
  :participaciones => 77,
  :goles => 2,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Yvon",
  :apellido => "Mvogo",
  :fecha_nacimiento => Date.new(1994,6,6),
  :ciudad_nacimiento => "Yaounde - Senegal",
  :posicion => "Portero",
  :dorsal => 12,
  :apodo => "N/A",
  :debut =>  Date.new(2018,6,8),
  :participaciones => 0,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Ricardo",
  :apellido => "Rodriguez",
  :fecha_nacimiento => Date.new(1992,8,25),
  :ciudad_nacimiento => "Zürich",
  :posicion => "Defensa",
  :dorsal => 13,
  :apodo => "N/A",
  :debut =>  Date.new(2011,10,7),
  :participaciones => 53,
  :goles => 3,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Steven",
  :apellido => "Zuber",
  :fecha_nacimiento => Date.new(1991,8,17),
  :ciudad_nacimiento => "Winterthur",
  :posicion => "Mediocampista",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2017,3,25),
  :participaciones => 10,
  :goles => 3,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Blerim",
  :apellido => "Dzemaili",
  :fecha_nacimiento => Date.new(1986,4,12),
  :ciudad_nacimiento => "Tetovo-Yugoslavia",
  :posicion => "Mediocampista",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2006,1,3),
  :participaciones => 63,
  :goles => 10,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Gelson",
  :apellido => "Fernandes",
  :fecha_nacimiento => Date.new(1986,9,3),
  :ciudad_nacimiento => "Praia-Cabo Verde",
  :posicion => "Mediocampista",
  :dorsal => 16,
  :apodo => "N/A",
  :debut =>  Date.new(2007,8,22),
  :participaciones => 66,
  :goles => 2,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "  Denis",
  :apellido => "Zakaria",
  :fecha_nacimiento => Date.new(1996,11,20),
  :ciudad_nacimiento => "Genf",
  :posicion => "Mediocampista",
  :dorsal => 17,
  :apodo => "N/A",
  :debut =>  Date.new(2016,8,25),
  :participaciones => 9,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Mario",
  :apellido => "Gavranovic",
  :fecha_nacimiento => Date.new(1989,11,24),
  :ciudad_nacimiento => "Lugano",
  :posicion => "Delantero",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  Date.new(2011,3,26),
  :participaciones => 13,
  :goles => 5,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Josip",
  :apellido => "Drmic",
  :fecha_nacimiento => Date.new(1992,8,8),
  :ciudad_nacimiento => "Bäch/Freienbach SZ",
  :posicion => "Delantero",
  :dorsal => 19,
  :apodo => "N/A",
  :debut =>  Date.new(2012,11,9),
  :participaciones => 27,
  :goles => 9,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Moussa",
  :apellido => "Konaté",
  :fecha_nacimiento => Date.new(1987,1,18),
  :ciudad_nacimiento => "Abidjan-Costa de Marfil",
  :posicion => "Defensa",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2006,1,3),
  :participaciones => 73,
  :goles => 2,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Roman",
  :apellido => "Burki",
  :fecha_nacimiento => Date.new(1990,11,14),
  :ciudad_nacimiento => "Munsingen",
  :posicion => "Portero",
  :dorsal => 21,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,18),
  :participaciones => 8,
  :goles => 0,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Xherdan",
  :apellido => "Shaqiri",
  :fecha_nacimiento => Date.new(1991,10,10),
  :ciudad_nacimiento => "Gjilan",
  :posicion => "Delantero",
  :dorsal => 23,
  :apodo => "N/A",
  :debut =>  Date.new(2010,3,3),
  :participaciones => 68,
  :goles => 20,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Fabian",
  :apellido => "Schar",
  :fecha_nacimiento => Date.new(1991,12,20),
  :ciudad_nacimiento => "Wil",
  :posicion => "Defensa",
  :dorsal => 22,
  :apodo => "N/A",
  :debut =>  Date.new(2013,8,14),
  :participaciones => 37,
  :goles => 7,
  :country_id => sui.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
}])
