# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
uru = Country.create(
  :nombre => 'Uruguay', 
  :apodo => 'Charrúas', 
  :grupo => 'A', 
  :escudo => 'public/countries/UruLo.png', 
  :bandera => '../assets/banderas/uruguay')

@uruG = uru

uru_coa = Coach.create(#Uruguay
  :nombre => "Washington",
  :apellido => "Tabárez",
  :apodo => "Maestro",
  :fecha_nacimiento => Date.new(1947,3,3),
  :ciudad_nacimiento => "Montevideo")

CoachTeam.create(
  :debut => Date.new(2006,2,13),
  :coach_id => uru_coa.id,
  :country_id  => uru.id)

Player.create([{#URUGUAY
  :nombre => "Fernando",
  :apellido => "Muslera",
  :fecha_nacimiento => Date.new(1996,06,16),
  :ciudad_nacimiento => "Buenos Aires",
  :posicion => "Portero",
  :dorsal => 1,
  :apodo => "El nene",
  :debut =>  Date.new(2009,10,10),
  :participaciones => 96,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Martin",
  :apellido => "Silva",
  :fecha_nacimiento => Date.new(1983,3,25),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Portero",
  :dorsal => 23,
  :apodo => "Superman",
  :debut =>  Date.new(2009,8,12),
  :participaciones => 11,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
  :nombre => "Martin",
  :apellido => "Campaña",
  :fecha_nacimiento => Date.new(1989,5,29),
  :ciudad_nacimiento => "Maldonado",
  :posicion => "Portero",
  :dorsal => 25,
  :apodo => "El Muro",
  :debut =>  Date.new(2016,5,28),
  :participaciones => 2,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Diego",
  :apellido => "Godin",
  :fecha_nacimiento => Date.new(1986,2,16),
  :ciudad_nacimiento => "Rosario",
  :posicion => "Defensa",
  :dorsal => 3,
  :apodo => "N/A",
  :debut =>  Date.new(2005,10,26),
  :participaciones => 115,
  :foto => "Picture",
  :goles => 8,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Jose",
  :apellido => "Giménez",
  :fecha_nacimiento => Date.new(1995,1,20),
  :ciudad_nacimiento => "Toledo",
  :posicion => "Defensa",
  :dorsal => 2,
  :apodo => "N/A",
  :debut =>  Date.new(2013,9,10),
  :participaciones => 41,
  :foto => "Picture",
  :goles => 4,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Sebastian",
  :apellido => "Coates",
  :fecha_nacimiento => Date.new(1990,10,7),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Defensa",
  :dorsal => 4,
  :apodo => "Seba",
  :debut =>  Date.new(2011,6,23),
  :participaciones => 30,
  :foto => "Picture",
  :goles => 1,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Gastón",
  :apellido => "Silva",
  :fecha_nacimiento => Date.new(1994,3,5),
  :ciudad_nacimiento => "Salto",
  :posicion => "Defensa",
  :dorsal => 13,
  :apodo => "Samurai",
  :debut =>  Date.new(2014,10,13),
  :participaciones => 12,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Maximiliano",
  :apellido => "Pereira",
  :fecha_nacimiento => Date.new(1984,6,8),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Defensa",
  :dorsal => 16,
  :apodo => "Mono",
  :debut =>  Date.new(2005,10,26),
  :participaciones => 124,
  :foto => "Picture",
  :goles => 3,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Guillermo",
  :apellido => "Valera",
  :fecha_nacimiento => Date.new(1993,3,24),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Defensa",
  :dorsal => 24,
  :apodo => "N/A",
  :debut =>  Date.new(2017,10,14),
  :participaciones => 3,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Martin",
  :apellido => "Cáceres",
  :fecha_nacimiento => Date.new(1987,4,7),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Defensa",
  :dorsal => 22,
  :apodo => "Pelado",
  :debut =>  Date.new(2007,9,12),
  :participaciones => 75,
  :foto => "Picture",
  :goles => 4,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Nahitan",
  :apellido => "Nández",
  :fecha_nacimiento => Date.new(1995,12,28),
  :ciudad_nacimiento => "Punta del Este",
  :posicion => "Mediocampista",
  :dorsal => 8,
  :apodo => "EL León",
  :debut =>  Date.new(2015,9,8),
  :participaciones => 11,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Lucas",
  :apellido => "Torreira",
  :fecha_nacimiento => Date.new(1996,2,11),
  :ciudad_nacimiento => "Fray Bentos",
  :posicion => "Mediocampista",
  :dorsal => 14,
  :apodo => "N/A",
  :debut =>  Date.new(2018,3,23),
  :participaciones => 2,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Matías",
  :apellido => "Vecino",
  :fecha_nacimiento => Date.new(1991,8,24),
  :ciudad_nacimiento => "San Jacinto",
  :posicion => "Mediocampista",
  :dorsal => 15,
  :apodo => "N/A",
  :debut =>  Date.new(2016,3,25),
  :participaciones => 21,
  :foto => "Picture",
  :goles => 1,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Rodrigo",
  :apellido => "Betancur",
  :fecha_nacimiento => Date.new(1997,6,25),
  :ciudad_nacimiento => "Nueva Helvecia",
  :posicion => "Mediocampista",
  :dorsal => 6,
  :apodo => "El Flaco",
  :debut =>  Date.new(2017,10,5),
  :participaciones => 6,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Carlos",
  :apellido => "Sanchez",
  :fecha_nacimiento => Date.new(1984,12,2),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Mediocampista",
  :dorsal => 5,
  :apodo => "N/A",
  :debut =>  Date.new(2014,11,14),
  :participaciones => 34,
  :foto => "Picture",
  :goles => 1,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Giogian",
  :apellido => "De Arrascaeta",
  :fecha_nacimiento => Date.new(1994,6,1),
  :ciudad_nacimiento => "Nuevo Berlin",
  :posicion => "Mediocampista",
  :dorsal => 10,
  :apodo => "Cocho",
  :debut =>  Date.new(2014,9,8),
  :participaciones => 7,
  :foto => "Picture",
  :goles => 1,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Diego",
  :apellido => "Laxalt",
  :fecha_nacimiento => Date.new(1993,2,7),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Mediocampista",
  :dorsal => 20,
  :apodo => "N/A",
  :debut =>  Date.new(2016,3,16),
  :participaciones => 5,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Cristian",
  :apellido => "Rodriguez",
  :fecha_nacimiento => Date.new(1985,9,30),
  :ciudad_nacimiento => "Juan Lacaze",
  :posicion => "Mediocampista",
  :dorsal => 7,
  :apodo => "Cebolla",
  :debut =>  Date.new(2009,12,11),
  :participaciones => 104,
  :foto => "Picture",
  :goles => 11,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Jonathan",
  :apellido => "Urretaviscaya",
  :fecha_nacimiento => Date.new(1990,3,19),
  :ciudad_nacimiento => "Montevideo",
  :posicion => "Mediocampista",
  :dorsal => 20,
  :apodo => "Urreta",
  :debut =>  Date.new(2017,10,14),
  :participaciones => 4,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Cristhiian",
  :apellido => "Stuani",
  :fecha_nacimiento => Date.new(1986,10,12),
  :ciudad_nacimiento => "Tala",
  :posicion => "Delantero",
  :dorsal => 11,
  :apodo => "ST7",
  :debut =>  Date.new(2012,11,14),
  :participaciones => 37,
  :foto => "Picture",
  :goles => 5,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Maximiliano",
  :apellido => "Gómez",
  :fecha_nacimiento => Date.new(1996,8,14),
  :ciudad_nacimiento => "Paysandú",
  :posicion => "Delantero",
  :dorsal => 18,
  :apodo => "N/A",
  :debut =>  Date.new(2017,2,28),
  :participaciones => 2,
  :foto => "Picture",
  :goles => 0,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Edison",
  :apellido => "Cavani",
  :fecha_nacimiento => Date.new(1987,2,14),
  :ciudad_nacimiento => "Salto",
  :posicion => "Delantero",
  :dorsal => 21,
  :apodo => "El Matador",
  :debut =>  Date.new(2008,2,6),
  :participaciones => 100,
  :foto => "Picture",
  :goles => 42,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
},
{
:nombre => "Luis",
  :apellido => "Suárez",
  :fecha_nacimiento => Date.new(1987,1,24),
  :ciudad_nacimiento => "Salto",
  :posicion => "Delantero",
  :dorsal => 9,
  :apodo => "Lucho",
  :debut =>  Date.new(2007,2,7),
  :participaciones => 97,
  :foto => "Picture",
  :goles => 50,
  :country_id => uru.id,
  :created_at => Date.new(2018,6,6),
  :updated_at => Date.new(2018,6,6)
}])